Repository grammyjs/website, pull requests merged in 2021-12, with the labels that each got.

#148 [Fix] [Translations] [English]: Syntax fix and format tip section
  site/docs/advanced/deployment.md
Labels: not translatable

#151 Improve code example of message sender type detection
  site/docs/guide/filter-queries.md
  site/docs/zh/guide/filter-queries.md
Labels: ready for translation, :cn: ZH

#165 Document workflow in contribution guide
  CONTRIBUTING.md
Labels: not translatable

#166 Improve Deploy Preview config in CI
  .github/workflows/deno.yml
Labels: not translatable

#168 Update Algolia Key
  site/docs/.vuepress/config.ts
Labels: not translatable

#164 Add guide for PM2
  site/docs/hosting/vps.md
  site/docs/zh/hosting/vps.md
Labels: ready for translation, :cn: ZH

#162 feat: Keyboard to custom keyboard renaming and improvements
  site/docs/.vuepress/config.ts
  site/docs/plugins/keyboard.md
  site/docs/zh/plugins/keyboard.md
Labels: ready for translation, :cn: ZH

#173 feat: Sync #150 to Chinese
  site/docs/zh/guide/files.md
Labels: :cn: ZH

#146 Add guide to writing plugins
  .github/workflows/deno.yml
  site/docs/.vuepress/config.ts
  site/docs/plugins/README.md
  site/docs/plugins/guide.md
  site/docs/zh/plugins/README.md
  site/docs/zh/plugins/guide.md
Labels: ready for translation, :cn: ZH

#161 fix: Do not use two English branches
  site/docs/advanced/deployment.md
Labels: not translatable

#175 Move built-in plugins to separate section
  site/docs/.vuepress/config.ts
Labels: ready for translation

#183 Do not repeat built-in
  site/docs/.vuepress/config.ts
Labels: ready for translation, :cn: ZH

#191 Fix typo in middleware explanation
  site/docs/guide/middleware.md
  site/docs/zh/guide/middleware.md
Labels: ready for translation, :cn: ZH

#193 update(faq.md): fix error grammar on link
  site/docs/zh/resources/faq.md
Labels: not translatable, :cn: ZH

#194 Fetch all commits during CI checkout
  .github/workflows/deno.yml
Labels: not translatable
