Repository grammyjs/website, pull requests merged in 2022-07, with the labels that each got.

#423 Update example for menu payload
  site/docs/plugins/menu.md
Labels: ready for translation

#429 Fix typo
  site/docs/es/guide/commands.md
  site/docs/guide/commands.md
  site/docs/zh/guide/commands.md
Labels: typo, ready for translation, :es: ES, :cn: ZH

#430 Translate menu payload
  site/docs/es/plugins/menu.md
  site/docs/plugins/menu.md
  site/docs/zh/plugins/menu.md
Labels: ready for translation, :es: ES, :cn: ZH

#432 Describe receiving `file_id` when sending files
  site/docs/es/guide/files.md
  site/docs/guide/files.md
  site/docs/zh/guide/files.md
Labels: ready for translation, :es: ES, :cn: ZH

#436 specific changes for Mac users
  .gitignore
Labels: not translatable

#438 Run deno fmt on Deno 1.24.0
  notifier/db.ts
  site/docs/es/plugins/emoji.md
Labels: not translatable

#440 Add Prisma storage adapter
  site/docs/es/plugins/session.md
  site/docs/plugins/session.md
  site/docs/zh/plugins/session.md
Labels: :es: ES, :cn: ZH

#443 Fix wrong property name
  site/docs/es/guide/context.md
  site/docs/guide/context.md
  site/docs/zh/guide/context.md
Labels: :es: ES, :cn: ZH

#445 Syntax correction for JS example
  site/docs/advanced/scaling.md
  site/docs/es/advanced/scaling.md
  site/docs/zh/advanced/scaling.md
Labels: :es: ES, :cn: ZH

#446 Don't deploy the notifier for forks
  .github/workflows/deploy.yml
Labels: not translatable

#448 Exclude `a` and `the` from links
  CONTRIBUTING.md
  TRANSLATING.md
  notifier/README.md
  site/docs/advanced/deployment.md
  site/docs/advanced/flood.md
  site/docs/advanced/reliability.md
  site/docs/advanced/scaling.md
  site/docs/advanced/transformers.md
  site/docs/es/guide/files.md
  site/docs/guide/README.md
  site/docs/guide/basics.md
  site/docs/guide/errors.md
  site/docs/guide/files.md
  site/docs/guide/filter-queries.md
  site/docs/hosting/comparison.md
  site/docs/plugins/auto-retry.md
  site/docs/plugins/guide.md
  site/docs/plugins/keyboard.md
  site/docs/plugins/menu.md
  site/docs/plugins/session.md
  site/docs/resources/comparison.md
  site/docs/resources/faq.md
Labels: not translatable, style

#449 Exclude articles from Spanish links
  site/docs/es/advanced/flood.md
  site/docs/es/advanced/reliability.md
  site/docs/es/advanced/scaling.md
  site/docs/es/advanced/transformers.md
  site/docs/es/guide/README.md
  site/docs/es/guide/basics.md
  site/docs/es/guide/errors.md
  site/docs/es/guide/files.md
  site/docs/es/guide/filter-queries.md
  site/docs/es/guide/introduction.md
  site/docs/es/hosting/comparison.md
  site/docs/es/plugins/auto-retry.md
  site/docs/es/plugins/guide.md
  site/docs/es/plugins/keyboard.md
  site/docs/es/plugins/menu.md
  site/docs/es/plugins/session.md
  site/docs/es/plugins/stateless-question.md
  site/docs/es/resources/comparison.md
  site/docs/es/resources/faq.md
Labels: not translatable, :es: ES, style

#439 Highlight modified lines (#433)
  site/docs/es/hosting/heroku.md
  site/docs/hosting/heroku.md
  site/docs/zh/hosting/heroku.md
Labels: ready for translation, :es: ES, :cn: ZH

#450 Fix Spanish link anchors
  site/docs/es/advanced/deployment.md
  site/docs/es/advanced/flood.md
  site/docs/es/advanced/middleware.md
  site/docs/es/advanced/scaling.md
  site/docs/es/guide/api.md
  site/docs/es/guide/basics.md
  site/docs/es/guide/context.md
  site/docs/es/guide/deployment-types.md
  site/docs/es/guide/errors.md
  site/docs/es/guide/files.md
  site/docs/es/guide/filter-queries.md
  site/docs/es/guide/games.md
  site/docs/es/guide/introduction.md
  site/docs/es/hosting/supabase.md
  site/docs/es/plugins/fluent.md
  site/docs/es/plugins/keyboard.md
  site/docs/es/plugins/menu.md
  site/docs/es/plugins/middlewares.md
  site/docs/es/plugins/ratelimiter.md
  site/docs/es/plugins/session.md
Labels: typo, not translatable, :es: ES
