Repository grammyjs/website, pull requests merged in 2022-04, with the labels that each got.

#269 docs(guide): code grouping package managers
  site/docs/guide/getting-started.md
  site/docs/zh/guide/getting-started.md
Labels: ready for translation, :cn: ZH

#267 Add proxy guide for Deno
  site/docs/advanced/proxy.md
  site/docs/zh/advanced/proxy.md
Labels: ready for translation, :cn: ZH

#272 Talk about a TypeScript build error in the FAQ
  site/docs/resources/faq.md
  site/docs/zh/resources/faq.md
Labels: ready for translation, :cn: ZH

#274 Update throttler docs
  site/docs/plugins/transformer-throttler.md
  site/docs/zh/plugins/transformer-throttler.md
Labels: :cn: ZH

#275 Add About page
  .vscode/settings.json
  site/docs/.vuepress/config.ts
  site/docs/resources/about.md
  site/docs/resources/faq.md
  site/docs/zh/resources/about.md
  site/docs/zh/resources/faq.md
Labels: ready for translation, :cn: ZH

#277 Rename .github/workflows/algolia.yml to .github/workflows-algolia.yml
  .github/workflows-algolia.yml
Labels: not translatable

#268 Better emoji plugin documentation
  site/docs/plugins/emoji.md
Labels: ready for translation

#279 Sync #268 documentation
  site/docs/zh/plugins/emoji.md
Labels: :cn: ZH

#282 Use esm.sh and not skypack.dev
  site/docs/guide/context.md
  site/docs/plugins/auto-retry.md
  site/docs/zh/guide/context.md
  site/docs/zh/plugins/auto-retry.md
Labels: not translatable

#285 Deno.File → Deno.FsFile
  site/docs/guide/files.md
  site/docs/zh/guide/files.md
Labels: :cn: ZH

#287 Brutal honesty :(
  TRANSLATING.md
Labels: not translatable

#288 Follow one sentence per line
  README.md
Labels: not translatable

#280 Resort the session plugin list
  site/docs/plugins/session.md
  site/docs/zh/plugins/session.md
Labels: ready for translation, :cn: ZH

#290 Fix casing in titles
  CONTRIBUTING.md
  site/docs/advanced/reliability.md
Labels: not translatable

#289 Add guide on sending media files
  site/docs/guide/api.md
  site/docs/guide/basics.md
  site/docs/guide/context.md
  site/docs/guide/files.md
  site/docs/guide/games.md
  site/docs/guide/inline-queries.md
  site/docs/zh/guide/api.md
  site/docs/zh/guide/basics.md
  site/docs/zh/guide/context.md
  site/docs/zh/guide/files.md
  site/docs/zh/guide/games.md
  site/docs/zh/guide/inline-queries.md
Labels: ready for translation, :cn: ZH

#292 Follow one sentence per line
  site/docs/advanced/transformers.md
  site/docs/guide/context.md
  site/docs/guide/deployment-types.md
  site/docs/guide/files.md
  site/docs/guide/filter-queries.md
  site/docs/guide/inline-queries.md
  site/docs/hosting/vps.md
  site/docs/plugins/console-time.md
  site/docs/plugins/emoji.md
  site/docs/plugins/keyboard.md
  site/docs/plugins/middlewares.md
  site/docs/plugins/ratelimiter.md
Labels: not translatable

#315 Fix typo
  site/docs/plugins/session.md
Labels: not translatable

#317 Fix typo
  site/docs/plugins/session.md
Labels: not translatable
