Repository grammyjs/website, pull requests merged in 2022-12, with the labels that each got.

#558 Fix comments
  site/docs/es/guide/games.md
  site/docs/es/hosting/comparison.md
  site/docs/es/hosting/fly.md
  site/docs/es/plugins/README.md
  site/docs/hosting/comparison.md
  site/docs/hosting/fly.md
  site/docs/id/hosting/comparison.md
  site/docs/id/hosting/fly.md
Labels: ready for translation, :es: ES, :indonesia: ID

#560 [WEBHOOKS] List of adapters and supported frameworks
  site/docs/es/guide/deployment-types.md
  site/docs/guide/deployment-types.md
  site/docs/id/guide/deployment-types.md
Labels: ready for translation, :es: ES, :indonesia: ID

#561 Be more clear about custom context property names
  site/docs/es/guide/context.md
  site/docs/guide/context.md
  site/docs/id/guide/context.md
Labels: ready for translation, :es: ES, :indonesia: ID

#567 fix: use title case
  site/docs/plugins/hydrate.md
Labels: typo, not translatable, style

#564 Add a note and link to documentation on systemd unit files
  site/docs/es/hosting/vps.md
  site/docs/hosting/vps.md
  site/docs/id/hosting/vps.md
Labels: ready for translation, :es: ES, :indonesia: ID

#563 feat: add section about mutli sessions with conversations
  site/docs/es/plugins/conversations.md
  site/docs/id/advanced/deployment.md
  site/docs/id/plugins/conversations.md
  site/docs/id/plugins/session.md
  site/docs/plugins/conversations.md
Labels: ready for translation, :es: ES, :indonesia: ID

#565 Fix property name
  site/docs/es/plugins/session.md
  site/docs/id/plugins/session.md
  site/docs/plugins/session.md
Labels: not translatable

#569 chore: alter translation guard's behavior
  .github/workflows/translation-guard.yml
Labels: not translatable

#557 Update Heroku pricing
  site/docs/es/hosting/comparison.md
  site/docs/es/hosting/heroku.md
  site/docs/hosting/comparison.md
  site/docs/hosting/heroku.md
  site/docs/id/hosting/comparison.md
  site/docs/id/hosting/heroku.md
Labels: ready for translation, :es: ES, :indonesia: ID

#571 Fix multiple Heroku entries in Spanish comparison table
  site/docs/es/hosting/comparison.md
Labels: typo, not translatable

#520 Update parse mode plugin docs
  site/docs/es/plugins/parse-mode.md
  site/docs/id/plugins/parse-mode.md
  site/docs/plugins/parse-mode.md
Labels: ready for translation, :es: ES, :indonesia: ID

#497 Document `ctx.entities()`
  site/docs/es/guide/context.md
  site/docs/guide/context.md
  site/docs/id/guide/context.md
Labels: ready for translation, :es: ES, :indonesia: ID, to merge on release

#568 feat: document `conversation.run` and `conversation.session`
  site/docs/es/plugins/conversations.md
  site/docs/id/plugins/conversations.md
  site/docs/plugins/conversations.md
Labels: ready for translation, :es: ES, :indonesia: ID

#572 fix: link to custom context type from structuring
  site/docs/advanced/structuring.md
  site/docs/es/advanced/structuring.md
  site/docs/id/advanced/structuring.md
Labels: ready for translation, :es: ES, :indonesia: ID

#575 feat: add support for Bot API 6.4
  site/docs/README.md
  site/docs/es/README.md
  site/docs/es/plugins/keyboard.md
  site/docs/id/README.md
  site/docs/id/plugins/keyboard.md
  site/docs/plugins/keyboard.md
Labels: ready for translation, :es: ES, :indonesia: ID, to merge on release
