Repository grammyjs/website, pull requests merged in 2022-06, with the labels that each got.

#414 Document more bad cases for missing await keywords
  site/docs/es/guide/middleware.md
  site/docs/guide/middleware.md
  site/docs/zh/guide/middleware.md
Labels: ready for translation, :es: ES, :cn: ZH

#420 Fix typo in session documentation
  site/docs/plugins/session.md
Labels: not translatable

#418 Fix duplicate link descriptions
  site/docs/es/guide/deployment-types.md
  site/docs/guide/deployment-types.md
  site/docs/zh/guide/deployment-types.md
Labels: ready for translation, :es: ES, :cn: ZH

#422 Fix formatting for Deno 1.23
  site/docs/es/plugins/fluent.md
  site/docs/plugins/fluent.md
  site/docs/zh/plugins/fluent.md
Labels: typo, not translatable

#424 Update to Bot API 6.1
  site/docs/README.md
Labels: ready for translation

#421 Replace Node with Deno in Deno code block
  site/docs/advanced/reliability.md
  site/docs/es/advanced/reliability.md
  site/docs/es/plugins/runner.md
  site/docs/plugins/runner.md
  site/docs/zh/advanced/reliability.md
  site/docs/zh/plugins/runner.md
Labels: ready for translation, :es: ES, :cn: ZH

#425 Sync #424 with Spanish
  site/docs/es/README.md
Labels: :es: ES

#426 Fix broken link to section
  site/docs/plugins/keyboard.md
Labels: not translatable

#428 Fix typo in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: not translatable
