Repository grammyjs/website, pull requests merged in 2022-05, with the labels that each got.

#293 [Feat] [Translations] [Spanish]: advanced/deployment
  site/docs/es/advanced/deployment.md
Labels: :es: ES

#294 [Feat] [Translations] [Spanish]: advanced/flood
  site/docs/es/advanced/flood.md
Labels: :es: ES

#295 [Feat] [Translations] [Spanish]: advanced/middleware
  site/docs/es/advanced/middleware.md
Labels: :es: ES

#237 [Feat] [Translations] [Spanish]: plugins/command-filter
  site/docs/es/plugins/command-filter.md
Labels: :es: ES

#263 [Feat] [Translations] [Spanish]: resources/comparison
  site/docs/es/resources/comparison.md
Labels: :es: ES

#262 [Feat] [Translations] [Spanish]: plugins/transformer-throttler
  site/docs/es/plugins/transformer-throttler.md
Labels: :es: ES

#261 [Feat] [Translations] [Spanish]: plugins/stateless-question
  site/docs/es/plugins/stateless-question.md
Labels: :es: ES

#259 [Feat] [Translations] [Spanish]: plugins/runner
  site/docs/es/plugins/runner.md
Labels: :es: ES

#297 [Feat] [Translations] [Spanish]: advanced/readme
  site/docs/es/advanced/README.md
Labels: :es: ES

#300 [Feat] [Translations] [Spanish]: advanced/structuring
  site/docs/es/advanced/structuring.md
Labels: :es: ES

#307 [Feat] [Translations] [Spanish]: guide/deployment-types
  site/docs/es/guide/deployment-types.md
Labels: :es: ES

#231 [Feat] [Translations] [Spanish]: hosting/deno-deploy
  site/docs/es/hosting/deno-deploy.md
Labels: :es: ES

#232 [Feat] [Translations] [Spanish]: hosting/gcf
  site/docs/es/hosting/gcf.md
Labels: :es: ES

#244 [Feat] [Translations] [Spanish]: plugins/i18n
  site/docs/es/plugins/i18n.md
Labels: :es: ES

#258 [Feat] [Translations] [Spanish]: plugins/router
  site/docs/es/plugins/router.md
Labels: :es: ES

#257 [Feat] [Translations] [Spanish]: plugins/README
  site/docs/es/plugins/README.md
Labels: :es: ES

#256 [Feat] [Translations] [Spanish]: plugins/ratelimiter
  site/docs/es/plugins/ratelimiter.md
Labels: :es: ES

#255 [Feat] [Translations] [Spanish]: plugins/parse-mode
  site/docs/es/plugins/parse-mode.md
Labels: :es: ES

#238 [Feat] [Translations] [Spanish]: plugins/console-time
  site/docs/es/plugins/console-time.md
Labels: :es: ES

#212 [Feat] [Translations] [Spanish]: guide/middleware
  site/docs/es/guide/middleware.md
Labels: :es: ES

#235 [Feat] [Translations] [Spanish]: hosting/heroku
  site/docs/es/hosting/heroku.md
Labels: :es: ES

#302 [Feat] [Translations] [Spanish]: demo/examples
  site/docs/es/demo/examples.md
Labels: :es: ES

#301 [Feat] [Translations] [Spanish]: advanced/transformers
  site/docs/es/advanced/transformers.md
Labels: :es: ES

#299 [Feat] [Translations] [Spanish]: advanced/scaling
  site/docs/es/advanced/scaling.md
Labels: :es: ES

#298 [Feat] [Translations] [Spanish]: advanced/reliability
  site/docs/es/advanced/reliability.md
Labels: :es: ES

#296 [Feat] [Translations] [Spanish]: advanced/proxy
  site/docs/es/advanced/proxy.md
Labels: :es: ES

#211 [Feat] [Translations] [Spanish]: guide/introduction
  site/docs/es/guide/introduction.md
Labels: :es: ES

#310 [Feat] [Translations] [Spanish]: demo/readme
  site/docs/es/demo/README.md
Labels: :es: ES

#264 [Feat] [Translations] [Spanish]: resources/faq
  site/docs/es/resources/faq.md
Labels: :es: ES

#260 [Feat] [Translations] [Spanish]: plugins/session
  site/docs/es/plugins/session.md
Labels: :es: ES

#323 Fix free storage links
  site/docs/plugins/session.md
  site/docs/zh/plugins/session.md
Labels: :cn: ZH

#254 [Feat] [Translations] [Spanish]: plugins/menu
  site/docs/es/plugins/menu.md
Labels: :es: ES

#253 [Feat] [Translations] [Spanish]: plugins/keyboard
  site/docs/es/plugins/keyboard.md
  site/docs/plugins/keyboard.md
Labels: :es: ES

#240 [Feat] [Translations] [Spanish]: plugins/hydrate
  site/docs/es/plugins/hydrate.md
Labels: :es: ES

#239 [Feat] [Translations] [Spanish]: plugins/files
  site/docs/es/plugins/files.md
Labels: :es: ES

#306 [Feat] [Translations] [Spanish]: guide/context
  site/docs/es/guide/context.md
Labels: :es: ES

#236 [Feat] [Translations] [Spanish]: plugins/auto-retry
  site/docs/es/plugins/auto-retry.md
Labels: :es: ES

#326 Revert "Let people without Deno format the docs (#325)"
  README.md
  site/package-lock.json
  site/package.json
Labels: not translatable

#329 Fix typo
  site/docs/guide/basics.md
Labels: not translatable

#330 AmE not BrE
  site/docs/guide/context.md
  site/docs/plugins/ratelimiter.md
  site/docs/plugins/session.md
Labels: not translatable

#332 Fix Chinese link reference
  site/docs/zh/guide/context.md
Labels: not translatable

#321 Describe how filter query logic and types can be reused
  site/docs/guide/filter-queries.md
  site/docs/zh/guide/filter-queries.md
Labels: ready for translation, :cn: ZH

#313 [Feat] [Translations] [Spanish]: guide/getting-started
  site/docs/es/guide/getting-started.md
Labels: :es: ES

#303 [Feat] [Translations] [Spanish]: guide/api
  site/docs/es/guide/api.md
Labels: :es: ES

#304 [Feat] [Translations] [Spanish]: guide/basics
  site/docs/es/guide/basics.md
Labels: :es: ES

#335 [Feat] [Translations] [Spanish]: guide/middleware (2)
  site/docs/es/guide/middleware.md
Labels: :es: ES

#314 [Feat] [Translations] [Spanish]: guide/inline-queries
  site/docs/es/guide/inline-queries.md
Labels: :es: ES

#312 [Feat] [Translations] [Spanish]: guide/games
  site/docs/es/guide/games.md
Labels: :es: ES

#311 [Feat] [Translations] [Spanish]: guide/filter-queries
  site/docs/es/guide/filter-queries.md
Labels: :es: ES

#308 [Feat] [Translations] [Spanish]: guide/errors
  site/docs/es/guide/errors.md
Labels: :es: ES

#336 No spaces around slash
  site/docs/plugins/console-time.md
Labels: not translatable

#337 Fix typo
  site/docs/resources/faq.md
Labels: not translatable

#340 Create grammY-showcase.svg
  logos/grammY-showcase.svg
Labels: not translatable

#342 Fix typo
  site/docs/resources/comparison.md
Labels: not translatable

#348 Increase deployment timeout to 5 minutes
  .github/workflows/build.yml
Labels: not translatable

#349 [Feat] [Translations] [Spanish]: plugins/middlewares
  site/docs/es/plugins/middlewares.md
Labels: :es: ES

#346 [Feat] [Translations] [Spanish]: plugins/fluent
  site/docs/es/plugins/fluent.md
Labels: :es: ES

#352 Run the build job recursively for `site/docs`
  .github/workflows/build.yml
Labels: not translatable

#354 Fix typo
  site/docs/plugins/session.md
Labels: not translatable

#353 Describe notifier in README
  README.md
Labels: not translatable

#344 [Feat] [Translations] [Spanish]: hosting/vps
  site/docs/es/hosting/vps.md
Labels: :es: ES

#347 [Feat] [Translations] [Spanish]: plugins/guide
  site/docs/es/plugins/guide.md
Labels: :es: ES

#355 Make action links consistent
  site/docs/README.md
  site/docs/zh/README.md
Labels: not translatable

#356 [Feat] [Translations] [Spanish]: plugins/ratelimiter (2)
  site/docs/es/plugins/ratelimiter.md
Labels: :es: ES

#351 [Feat] [Translations] [Spanish]: config
  site/docs/.vuepress/config.ts
  site/docs/es/README.md
Labels: :es: ES

#357 [Feat] [Translations] [Spanish]: hosting/deno-deploy (2)
  site/docs/es/hosting/deno-deploy.md
Labels: :es: ES

#358 Fix English action links
  site/docs/README.md
Labels: not translatable

#338 Update the Deno Deploy guide
  site/docs/hosting/deno-deploy.md
  site/docs/zh/hosting/deno-deploy.md
Labels: ready for translation, :es: ES, :cn: ZH

#364 Fix broken links in the index pages
  site/docs/es/README.md
  site/docs/zh/README.md
Labels: not translatable

#365 Update deps
  site/package-lock.json
  site/package.json
Labels: not translatable

#367 Fix broken links
  site/docs/es/guide/deployment-types.md
  site/docs/guide/deployment-types.md
  site/docs/zh/guide/deployment-types.md
Labels: not translatable

#366 Replace .md with .html in the links on the index pages
  site/docs/README.md
  site/docs/es/README.md
  site/docs/zh/README.md
Labels: not translatable

#350 Update Rate Limiter examples and add Deno ones
  site/docs/plugins/ratelimiter.md
  site/docs/zh/plugins/ratelimiter.md
Labels: ready for translation, :es: ES, :cn: ZH

#368 Alter the behavior of the Notifier
  notifier/.vscode/settings.json
  notifier/db.ts
  notifier/labels.json
  notifier/languages.ts
  notifier/mod.ts
Labels: not translatable

#373 Update translation guide
  TRANSLATING.md
Labels: not translatable

#375 Use exact Deno URLs
  site/docs/.vuepress/config.ts
  site/docs/.vuepress/plugins/better-line-breaks.ts
  site/docs/.vuepress/plugins/current-versions/.gitignore
  site/docs/.vuepress/plugins/current-versions/build-index.ts
  site/docs/.vuepress/plugins/current-versions/modules.json
  site/docs/.vuepress/plugins/current-versions/plugin.ts
  site/docs/.vuepress/plugins/docsearch.ts
  site/docs/.vuepress/plugins/shared.ts
  site/docs/es/guide/introduction.md
  site/docs/guide/introduction.md
  site/docs/zh/guide/introduction.md
  site/package.json
Labels: not translatable

#374 Create Plugin Summary for Stateless Question
  site/docs/es/plugins/stateless-question.md
  site/docs/plugins/stateless-question.md
  site/docs/zh/plugins/stateless-question.md
Labels: not translatable

#378 Fix typo
  site/docs/guide/deployment-types.md
Labels: not translatable

#377 Fix punctuation on Spanish landing page
  site/docs/es/README.md
Labels: not translatable

#379 Improve text justification
  site/docs/.vuepress/styles/index.scss
Labels: not translatable

#380 Remove senseless `console.log`s
  notifier/mod.ts
Labels: not translatable

#382 Fix active links
  site/docs/.vuepress/config.ts
Labels: not translatable

#383 Update styles for inline code in tables
  site/docs/.vuepress/styles/index.scss
Labels: not translatable

#385 Deploy the notifier only for pushes to `notifier/`
  .github/workflows/deploy.yml
Labels: not translatable

#362 Add a note about bot.start call
  site/docs/es/hosting/deno-deploy.md
  site/docs/hosting/deno-deploy.md
  site/docs/zh/guide/deployment-types.md
  site/docs/zh/hosting/deno-deploy.md
Labels: ready for translation, :es: ES, :cn: ZH

#387 Make the notifier pin the notifications
  notifier/languages.ts
  notifier/mod.ts
  notifier/utils.ts
Labels: not translatable

#389 Fix single-quote formatting in inline code snippets
  site/docs/advanced/deployment.md
  site/docs/advanced/middleware.md
  site/docs/advanced/structuring.md
  site/docs/es/advanced/deployment.md
  site/docs/es/advanced/middleware.md
  site/docs/es/advanced/structuring.md
  site/docs/es/guide/basics.md
  site/docs/es/guide/commands.md
  site/docs/es/guide/filter-queries.md
  site/docs/es/guide/inline-queries.md
  site/docs/es/plugins/console-time.md
  site/docs/es/plugins/files.md
  site/docs/es/plugins/keyboard.md
  site/docs/es/plugins/menu.md
  site/docs/es/plugins/router.md
  site/docs/es/plugins/stateless-question.md
  site/docs/guide/basics.md
  site/docs/guide/commands.md
  site/docs/guide/filter-queries.md
  site/docs/guide/inline-queries.md
  site/docs/plugins/console-time.md
  site/docs/plugins/files.md
  site/docs/plugins/keyboard.md
  site/docs/plugins/menu.md
  site/docs/plugins/router.md
  site/docs/plugins/stateless-question.md
  site/docs/zh/advanced/deployment.md
  site/docs/zh/advanced/middleware.md
  site/docs/zh/advanced/structuring.md
  site/docs/zh/guide/basics.md
  site/docs/zh/guide/commands.md
  site/docs/zh/guide/filter-queries.md
  site/docs/zh/guide/inline-queries.md
  site/docs/zh/plugins/console-time.md
  site/docs/zh/plugins/files.md
  site/docs/zh/plugins/keyboard.md
  site/docs/zh/plugins/menu.md
  site/docs/zh/plugins/router.md
  site/docs/zh/plugins/stateless-question.md
Labels: :es: ES, :cn: ZH

#334 Add Hosting Provider Comparison Table
  site/docs/.vuepress/config.ts
  site/docs/es/guide/introduction.md
  site/docs/es/hosting/comparison.md
  site/docs/guide/introduction.md
  site/docs/hosting/comparison.md
  site/docs/zh/guide/introduction.md
  site/docs/zh/hosting/comparison.md
Labels: ready for translation, :es: ES, :cn: ZH

#390 Remove lost English sentence in Spanish docs
  site/docs/.vuepress/plugins/better-line-breaks.ts
  site/docs/.vuepress/styles/index.scss
  site/docs/es/guide/files.md
Labels: not translatable

#392 Create logos/README.md
  logos/README.md
  logos/grammY-showcase.svg
Labels: not translatable

#395 Fix reference to hosting section
  site/docs/advanced/deployment.md
  site/docs/es/advanced/deployment.md
  site/docs/es/hosting/deno-deploy.md
  site/docs/es/hosting/gcf.md
  site/docs/es/hosting/heroku.md
  site/docs/es/hosting/vps.md
  site/docs/zh/advanced/deployment.md
Labels: :es: ES, :cn: ZH

#394 Insert `<wbr>` tags into links
  site/docs/.vuepress/plugins/better-line-breaks.ts
  site/docs/.vuepress/styles/index.scss
Labels: not translatable

#397 Fix Hosting Comparison links
  site/docs/.vuepress/config.ts
Labels: not translatable

#398 Revert "Document unified storage adapter installation method"
  site/docs/es/plugins/session.md
  site/docs/plugins/session.md
  site/docs/zh/plugins/session.md
Labels: not translatable

#384 Add router 2.0 docs
  site/docs/es/plugins/router.md
  site/docs/plugins/router.md
  site/docs/zh/plugins/router.md
Labels: ready for translation, :es: ES, :cn: ZH

#391 Convert colors to hex
  site/docs/.vuepress/styles/index.scss
Labels: not translatable

#401 fix(notifier): crash when no GitHub header is passed
  notifier/mod.ts
Labels: not translatable

#404 Remove empty example bot section from menu
  site/docs/.vuepress/config.ts
Labels: not translatable

#399 #393 II
  site/docs/es/plugins/session.md
  site/docs/plugins/session.md
  site/docs/zh/plugins/session.md
Labels: ready for translation, :es: ES, :cn: ZH

#408 Use local image files
  site/docs/.vuepress/public/inline-keyboard-example-1.webp
  site/docs/.vuepress/public/inline-keyboard-example-2.webp
  site/docs/.vuepress/public/inline-keyboard-example-3.webp
  site/docs/.vuepress/public/keyboard-example-1.webp
  site/docs/.vuepress/public/keyboard-example-2.webp
  site/docs/.vuepress/public/keyboard-example-3.webp
  site/docs/es/plugins/keyboard.md
  site/docs/plugins/keyboard.md
  site/docs/zh/plugins/keyboard.md
Labels: not translatable

#410 Move from single quotes to double quotes
  site/docs/es/guide/basics.md
  site/docs/es/guide/deployment-types.md
  site/docs/es/plugins/console-time.md
  site/docs/es/plugins/middlewares.md
  site/docs/guide/basics.md
  site/docs/guide/commands.md
  site/docs/guide/deployment-types.md
  site/docs/plugins/console-time.md
  site/docs/plugins/middlewares.md
  site/docs/zh/guide/basics.md
  site/docs/zh/guide/deployment-types.md
  site/docs/zh/plugins/console-time.md
  site/docs/zh/plugins/middlewares.md
Labels: not translatable

#411 Move from ' to "
  site/docs/es/guide/commands.md
  site/docs/es/guide/deployment-types.md
  site/docs/es/guide/filter-queries.md
  site/docs/es/guide/getting-started.md
  site/docs/es/guide/middleware.md
  site/docs/guide/commands.md
  site/docs/guide/deployment-types.md
  site/docs/guide/filter-queries.md
  site/docs/guide/getting-started.md
  site/docs/guide/middleware.md
  site/docs/zh/guide/context.md
  site/docs/zh/guide/filter-queries.md
  site/docs/zh/guide/getting-started.md
  site/docs/zh/guide/middleware.md
  site/docs/zh/hosting/deno-deploy.md
Labels: not translatable

#412 fix: non-translated phrase on keyboard plugin
  site/docs/es/plugins/keyboard.md
Labels: typo, not translatable, :es: ES

#413 Fix hoder typo
  site/docs/es/plugins/keyboard.md
  site/docs/plugins/keyboard.md
  site/docs/zh/plugins/keyboard.md
Labels: typo, not translatable

#406 Point URLs to localized guides
  site/docs/es/plugins/emoji.md
Labels: typo, not translatable, :es: ES

#388 Rewrite section about custom context flavors
  site/docs/es/guide/context.md
  site/docs/guide/context.md
  site/docs/zh/guide/context.md
Labels: ready for translation, :es: ES, :cn: ZH

#402 Improve explanation about installing menus
  site/docs/es/plugins/menu.md
  site/docs/plugins/menu.md
  site/docs/zh/plugins/menu.md
Labels: ready for translation, :es: ES, :cn: ZH

#405 Add section about when to use sessions
  site/docs/es/plugins/session.md
  site/docs/plugins/session.md
  site/docs/zh/plugins/session.md
Labels: ready for translation, :es: ES, :cn: ZH

#415 Follow one sentence per line in list items
  site/docs/es/hosting/heroku.md
  site/docs/es/plugins/ratelimiter.md
  site/docs/hosting/heroku.md
  site/docs/plugins/ratelimiter.md
Labels: not translatable

#403 Add Supabase Edge Functions tutorial
  site/docs/.vuepress/config.ts
  site/docs/es/hosting/deno-deploy.md
  site/docs/es/hosting/supabase.md
  site/docs/hosting/deno-deploy.md
  site/docs/hosting/supabase.md
  site/docs/zh/hosting/deno-deploy.md
  site/docs/zh/hosting/supabase.md
Labels: ready for translation, :es: ES, :cn: ZH

#416 Fix weird code order
  site/docs/es/guide/context.md
  site/docs/guide/context.md
  site/docs/zh/guide/context.md
Labels: not translatable

#417 Fix variables in Fluent plugin
  site/docs/es/plugins/fluent.md
  site/docs/plugins/fluent.md
  site/docs/zh/plugins/fluent.md
Labels: not translatable
