Repository grammyjs/website, pull requests merged in 2022-01, with the labels that each got.

#197 Fix Telegram chat link
  site/docs/advanced/scaling.md
  site/docs/zh/advanced/scaling.md
Labels: ready for translation, :cn: ZH

#198 Add JS examples to middleware section
  site/docs/guide/middleware.md
  site/docs/zh/guide/middleware.md
Labels: ready for translation, :cn: ZH

#201 Document the emoji plugin
  site/docs/.vuepress/config.ts
  site/docs/plugins/emoji.md
  site/docs/zh/plugins/emoji.md
Labels: ready for translation, :cn: ZH

#209 Fix typo in file plugin docs
  site/docs/plugins/files.md
Labels: typo, not translatable

#208 Updated to reflect bot api 5.6
  site/docs/README.md
  site/docs/guide/filter-queries.md
  site/docs/zh/README.md
  site/docs/zh/guide/filter-queries.md
Labels: ready for translation, :cn: ZH

#210 Add link from grammY FAQ to Bot FAQ
  site/docs/resources/faq.md
  site/docs/zh/resources/faq.md
Labels: typo, ready for translation, :cn: ZH

#214 Follow the Berne Convention in the (c) notices [1]
  LICENSE
  site/docs/README.md
  site/docs/zh/README.md
Labels: not translatable

#222 Make quotes consistent
  CONTRIBUTING.md
  site/docs/README.md
  site/docs/guide/deployment-types.md
  site/docs/guide/files.md
  site/docs/guide/games.md
  site/docs/plugins/ratelimiter.md
Labels: not translatable

#217 Add Translation Guide
  CONTRIBUTING.md
  TRANSLATING.md
Labels: not translatable

#223 Use normal quotes when referring to values
  site/docs/guide/files.md
  site/docs/guide/games.md
  site/docs/plugins/ratelimiter.md
Labels: not translatable

#224 typo correction
  site/docs/plugins/files.md
Labels: not translatable

#221 [Feat] [Translations] [Uzbek]: uz/advanced/readme
  site/docs/uz/advanced/README.md
Labels: 🇺🇿 UZ

#226 [Feat] [Translations] [Uzbek]: uz/advanced/middleware
  site/docs/uz/advanced/middleware.md
Labels: 🇺🇿 UZ

#227 [Feat] [Translations] [Uzbek]: uz/guide/readme
  site/docs/uz/guide/README.md
Labels: 🇺🇿 UZ

#220 Added note about editing keyboard and fixed a typo
  site/docs/plugins/keyboard.md
  site/docs/zh/plugins/keyboard.md
Labels: ready for translation, :cn: ZH
