Repository grammyjs/website, pull requests merged in 2022-08, with the labels that each got.

#444 Update comparison as time went by
  site/docs/es/resources/comparison.md
  site/docs/resources/comparison.md
  site/docs/zh/resources/comparison.md
Labels: ready for translation, :es: ES, :cn: ZH

#452 Document exported API types
  site/docs/es/guide/api.md
  site/docs/guide/api.md
Labels: ready for translation, :es: ES

#451 Update keyboard plugin docs
  site/docs/es/plugins/keyboard.md
  site/docs/plugins/keyboard.md
Labels: ready for translation, :es: ES

#331 Add conversation docs
  site/docs/.vuepress/config.ts
  site/docs/es/plugins/conversations.md
  site/docs/plugins/conversations.md
Labels: ready for translation, :es: ES

#458 Fix links
  site/docs/es/resources/comparison.md
  site/docs/resources/comparison.md
  site/docs/zh/advanced/reliability.md
  site/docs/zh/advanced/scaling.md
  site/docs/zh/advanced/transformers.md
  site/docs/zh/guide/filter-queries.md
  site/docs/zh/hosting/deno-deploy.md
  site/docs/zh/hosting/supabase.md
  site/docs/zh/plugins/README.md
  site/docs/zh/resources/comparison.md
Labels: typo, not translatable

#459 Fix navlink
  site/docs/.vuepress/config.ts
Labels: not translatable

#461 Fix plugin list order
  site/docs/.vuepress/config.ts
Labels: not translatable, :es: ES

#463 Fix examples repository links
  site/docs/es/hosting/supabase.md
  site/docs/hosting/supabase.md
  site/docs/zh/hosting/supabase.md
Labels: not translatable

#466 Fix typo
  site/docs/guide/api.md
Labels: typo, not translatable

#467 Drop redundant English config
  site/docs/.vuepress/config.ts
Labels: not translatable, chore

#469 Sync #451 and #452 with Chinese
  site/docs/zh/guide/api.md
  site/docs/zh/plugins/keyboard.md
Labels: not translatable, :cn: ZH

#470 Fix typo
  site/docs/hosting/deno-deploy.md
Labels: typo

#474 Fix typo and make title case consistent
  site/docs/plugins/session.md
Labels: not translatable

#456 Document chat join requests in hydrate plugin
  site/docs/es/plugins/hydrate.md
  site/docs/plugins/hydrate.md
  site/docs/zh/plugins/hydrate.md
Labels: ready for translation, :es: ES, :cn: ZH

#464 Update conversations and translate to Chinese
  site/docs/.vuepress/config.ts
  site/docs/es/plugins/conversations.md
  site/docs/plugins/conversations.md
  site/docs/zh/plugins/conversations.md
Labels: ready for translation, :es: ES, :cn: ZH

#476 Fix typos
  README.md
  TRANSLATING.md
  site/docs/advanced/scaling.md
  site/docs/advanced/structuring.md
  site/docs/advanced/transformers.md
  site/docs/guide/api.md
  site/docs/guide/deployment-types.md
  site/docs/hosting/heroku.md
  site/docs/hosting/supabase.md
  site/docs/hosting/vps.md
  site/docs/plugins/auto-retry.md
  site/docs/plugins/conversations.md
  site/docs/plugins/emoji.md
  site/docs/plugins/guide.md
  site/docs/plugins/i18n.md
  site/docs/plugins/menu.md
  site/docs/plugins/middlewares.md
  site/docs/resources/comparison.md
Labels: good first contribution

#479 MASSIVE FIX
  site/docs/guide/context.md
Labels: typo, not translatable

#441 Document roziscoding/grammy-autoquote
  site/docs/.vuepress/config.ts
  site/docs/.vuepress/plugins/current-versions/modules.json
  site/docs/plugins/autoquote.md
  site/docs/zh/plugins/autoquote.md
Labels: ready for translation, :cn: ZH

#482 Document roziscoding/grammy-autoquote (#441)
  site/docs/.vuepress/config.ts
  site/docs/.vuepress/plugins/current-versions/modules.json
  site/docs/es/plugins/autoquote.md
  site/docs/plugins/autoquote.md
  site/docs/zh/plugins/autoquote.md
Labels: ready for translation, :es: ES, :cn: ZH

#488 Fix typo
  site/docs/es/hosting/vps.md
  site/docs/hosting/vps.md
  site/docs/zh/hosting/vps.md
Labels: :es: ES, :cn: ZH

#471 Fix typo
  site/docs/es/plugins/conversations.md
  site/docs/plugins/conversations.md
  site/docs/zh/plugins/conversations.md
Labels: :es: ES, :cn: ZH
