Repository grammyjs/website, pull requests merged in 2022-11, with the labels that each got.

#535 Fix syntax
  site/docs/es/plugins/conversations.md
  site/docs/id/plugins/conversations.md
  site/docs/plugins/conversations.md
  site/docs/zh/plugins/conversations.md
Labels: :es: ES, :cn: ZH, :indonesia: ID

#538 Okay okay fine we'll update it
  site/docs/README.md
  site/docs/id/README.md
Labels: ready for translation, :indonesia: ID

#540 Fix missing the
  site/docs/guide/deployment-types.md
Labels: not translatable

#541 Update notifier deps
  .github/workflows/deploy.yml
  notifier/db.ts
  notifier/deno.json
  notifier/deno.lock
  notifier/env.ts
  notifier/import_map.json
  notifier/main.ts
  notifier/utils.ts
Labels: not translatable

#504 Add section about installing conversations with custom session data
  site/docs/es/plugins/conversations.md
  site/docs/es/plugins/session.md
  site/docs/id/plugins/conversations.md
  site/docs/plugins/conversations.md
  site/docs/zh/plugins/conversations.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID

#544 Create translation-guard.yml
  .github/workflows/translation-guard.yml
Labels: not translatable

#546 Fix typo
  site/docs/plugins/menu.md
Labels: typo, not translatable

#542 Translations: API 6.3
  site/docs/es/README.md
Labels: ready for translation, :es: ES, :indonesia: ID

#530 Add note to router forms
  site/docs/es/plugins/router.md
  site/docs/id/plugins/router.md
  site/docs/plugins/router.md
Labels: ready for translation, :es: ES, :indonesia: ID

#516 Add `Enhance` types to the session docs (#502)
  site/docs/es/plugins/session.md
  site/docs/id/plugins/session.md
  site/docs/plugins/session.md
Labels: ready for translation, :es: ES, :indonesia: ID

#513 Describe how to catch errors when leaving conversations by throwing
  site/docs/es/plugins/conversations.md
  site/docs/id/plugins/conversations.md
  site/docs/plugins/conversations.md
  site/package-lock.json
Labels: ready for translation, :es: ES, :indonesia: ID

#506 Add Fly to the hosting comparison
  site/docs/es/hosting/comparison.md
  site/docs/hosting/comparison.md
  site/docs/id/hosting/comparison.md
Labels: ready for translation, :es: ES, :indonesia: ID

#547 Remove Chinese translations
  TRANSLATING.md
  site/docs/.vuepress/config.ts
  site/docs/zh/README.md
  site/docs/zh/advanced/README.md
  site/docs/zh/advanced/deployment.md
  site/docs/zh/advanced/flood.md
  site/docs/zh/advanced/middleware.md
  site/docs/zh/advanced/proxy.md
  site/docs/zh/advanced/reliability.md
  site/docs/zh/advanced/scaling.md
  site/docs/zh/advanced/structuring.md
  site/docs/zh/advanced/transformers.md
  site/docs/zh/demo/README.md
  site/docs/zh/demo/examples.md
  site/docs/zh/guide/README.md
  site/docs/zh/guide/api.md
  site/docs/zh/guide/basics.md
  site/docs/zh/guide/commands.md
  site/docs/zh/guide/context.md
  site/docs/zh/guide/deployment-types.md
  site/docs/zh/guide/errors.md
  site/docs/zh/guide/files.md
  site/docs/zh/guide/filter-queries.md
  site/docs/zh/guide/games.md
  site/docs/zh/guide/getting-started.md
  site/docs/zh/guide/inline-queries.md
  site/docs/zh/guide/introduction.md
  site/docs/zh/guide/middleware.md
  site/docs/zh/hosting/comparison.md
  site/docs/zh/hosting/deno-deploy.md
  site/docs/zh/hosting/gcf.md
  site/docs/zh/hosting/heroku.md
  site/docs/zh/hosting/supabase.md
  site/docs/zh/hosting/vps.md
  site/docs/zh/plugins/README.md
  site/docs/zh/plugins/auto-retry.md
  site/docs/zh/plugins/autoquote.md
  site/docs/zh/plugins/command-filter.md
  site/docs/zh/plugins/console-time.md
  site/docs/zh/plugins/conversations.md
  site/docs/zh/plugins/emoji.md
  site/docs/zh/plugins/files.md
  site/docs/zh/plugins/fluent.md
  site/docs/zh/plugins/guide.md
  site/docs/zh/plugins/hydrate.md
  site/docs/zh/plugins/i18n.md
  site/docs/zh/plugins/keyboard.md
  site/docs/zh/plugins/menu.md
  site/docs/zh/plugins/middlewares.md
  site/docs/zh/plugins/parse-mode.md
  site/docs/zh/plugins/ratelimiter.md
  site/docs/zh/plugins/router.md
  site/docs/zh/plugins/runner.md
  site/docs/zh/plugins/session.md
  site/docs/zh/plugins/stateless-question.md
  site/docs/zh/plugins/transformer-throttler.md
  site/docs/zh/resources/about.md
  site/docs/zh/resources/comparison.md
  site/docs/zh/resources/faq.md
Labels: not translatable, :cn: ZH

#550 Remove Chinese
  TRANSLATING.md
  site/docs/.vuepress/config.ts
  site/docs/zh/README.md
  site/docs/zh/advanced/README.md
  site/docs/zh/advanced/deployment.md
  site/docs/zh/advanced/flood.md
  site/docs/zh/advanced/middleware.md
  site/docs/zh/advanced/proxy.md
  site/docs/zh/advanced/reliability.md
  site/docs/zh/advanced/scaling.md
  site/docs/zh/advanced/structuring.md
  site/docs/zh/advanced/transformers.md
  site/docs/zh/demo/README.md
  site/docs/zh/demo/examples.md
  site/docs/zh/guide/README.md
  site/docs/zh/guide/api.md
  site/docs/zh/guide/basics.md
  site/docs/zh/guide/commands.md
  site/docs/zh/guide/context.md
  site/docs/zh/guide/deployment-types.md
  site/docs/zh/guide/errors.md
  site/docs/zh/guide/files.md
  site/docs/zh/guide/filter-queries.md
  site/docs/zh/guide/games.md
  site/docs/zh/guide/getting-started.md
  site/docs/zh/guide/inline-queries.md
  site/docs/zh/guide/introduction.md
  site/docs/zh/guide/middleware.md
  site/docs/zh/hosting/comparison.md
  site/docs/zh/hosting/deno-deploy.md
  site/docs/zh/hosting/gcf.md
  site/docs/zh/hosting/heroku.md
  site/docs/zh/hosting/supabase.md
  site/docs/zh/hosting/vps.md
  site/docs/zh/plugins/README.md
  site/docs/zh/plugins/auto-retry.md
  site/docs/zh/plugins/autoquote.md
  site/docs/zh/plugins/command-filter.md
  site/docs/zh/plugins/console-time.md
  site/docs/zh/plugins/conversations.md
  site/docs/zh/plugins/emoji.md
  site/docs/zh/plugins/files.md
  site/docs/zh/plugins/fluent.md
  site/docs/zh/plugins/guide.md
  site/docs/zh/plugins/hydrate.md
  site/docs/zh/plugins/i18n.md
  site/docs/zh/plugins/keyboard.md
  site/docs/zh/plugins/menu.md
  site/docs/zh/plugins/middlewares.md
  site/docs/zh/plugins/parse-mode.md
  site/docs/zh/plugins/ratelimiter.md
  site/docs/zh/plugins/router.md
  site/docs/zh/plugins/runner.md
  site/docs/zh/plugins/session.md
  site/docs/zh/plugins/stateless-question.md
  site/docs/zh/plugins/transformer-throttler.md
  site/docs/zh/resources/about.md
  site/docs/zh/resources/comparison.md
  site/docs/zh/resources/faq.md
Labels: not translatable, chore

#551 Apply commits before Chinese was removed
  site/docs/es/hosting/comparison.md
  site/docs/es/plugins/conversations.md
  site/docs/es/plugins/router.md
  site/docs/es/plugins/session.md
  site/docs/hosting/comparison.md
  site/docs/id/hosting/comparison.md
  site/docs/id/plugins/conversations.md
  site/docs/id/plugins/router.md
  site/docs/id/plugins/session.md
  site/docs/plugins/conversations.md
  site/docs/plugins/router.md
  site/docs/plugins/session.md
  site/package-lock.json
Labels: not translatable, chore

#554 Improve translations and fix inconsistencies
  site/docs/es/plugins/auto-retry.md
  site/docs/es/plugins/emoji.md
  site/docs/es/plugins/hydrate.md
  site/docs/es/plugins/keyboard.md
  site/docs/es/plugins/parse-mode.md
  site/docs/es/plugins/ratelimiter.md
  site/docs/es/plugins/router.md
  site/docs/es/plugins/runner.md
  site/docs/es/plugins/session.md
  site/docs/es/plugins/stateless-question.md
  site/docs/es/plugins/transformer-throttler.md
Labels: not translatable

#442 Add plugin overview
  site/docs/es/plugins/README.md
  site/docs/id/plugins/README.md
  site/docs/plugins/README.md
Labels: ready for translation, :es: ES, :indonesia: ID

#518 these not there
  site/docs/es/plugins/session.md
  site/docs/plugins/session.md
Labels: ready for translation, :es: ES, :indonesia: ID

#555 Fix link and names across different files
  site/docs/es/guide/commands.md
  site/docs/es/guide/games.md
  site/docs/es/plugins/i18n.md
  site/docs/es/plugins/keyboard.md
  site/docs/es/plugins/menu.md
Labels: not translatable, :es: ES

#536 Add missing link
  site/docs/advanced/structuring.md
  site/docs/es/advanced/structuring.md
  site/docs/id/advanced/structuring.md
Labels: ready for translation, :es: ES, :indonesia: ID

#553 Unsync spanish translation from context file
  site/docs/es/guide/context.md
Labels: not translatable, :es: ES

#505 Add Fly hosting guide
  site/docs/.vuepress/config.ts
  site/docs/es/hosting/fly.md
  site/docs/hosting/fly.md
  site/docs/id/hosting/fly.md
Labels: ready for translation, :es: ES, :indonesia: ID

#545 Add Vercel hosting guide (#543)
  site/docs/.vuepress/config.ts
  site/docs/es/hosting/vercel.md
  site/docs/hosting/vercel.md
  site/docs/id/hosting/vercel.md
Labels: ready for translation, :es: ES, :indonesia: ID

#533 Refactor
  .gitignore
  .vscode/settings.json
  site/.npmrc
  site/docs/.vuepress/config.ts
  site/docs/.vuepress/configs/en.ts
  site/docs/.vuepress/configs/es.ts
  site/docs/.vuepress/configs/id.ts
  site/docs/.vuepress/configs/index.ts
  site/docs/.vuepress/styles/_code.scss
  site/docs/.vuepress/styles/_custom-container.scss
  site/docs/.vuepress/styles/_normalize.scss
  site/docs/.vuepress/styles/_vars-dark.scss
  site/docs/.vuepress/styles/_vars.scss
  site/docs/.vuepress/styles/index.scss
Labels: not translatable, chore

#556 Update Telegram links
  site/docs/es/guide/basics.md
  site/docs/es/guide/commands.md
  site/docs/es/guide/inline-queries.md
  site/docs/es/plugins/keyboard.md
  site/docs/es/plugins/session.md
  site/docs/es/plugins/stateless-question.md
  site/docs/guide/basics.md
  site/docs/guide/commands.md
  site/docs/guide/inline-queries.md
  site/docs/id/guide/basics.md
  site/docs/id/guide/commands.md
  site/docs/id/guide/inline-queries.md
  site/docs/id/plugins/keyboard.md
  site/docs/id/plugins/session.md
  site/docs/id/plugins/stateless-question.md
  site/docs/plugins/keyboard.md
  site/docs/plugins/session.md
  site/docs/plugins/stateless-question.md
Labels: ready for translation, :es: ES, :indonesia: ID

#511 Update config for docsearch plugin
  site/docs/.vuepress/configs/en.ts
  site/docs/.vuepress/configs/es.ts
Labels: ready for translation, :es: ES, :indonesia: ID
