Repository grammyjs/website, pull requests merged in 2022-10, with the labels that each got.

#524 Respond after exiting the conversation
  site/docs/es/plugins/conversations.md
  site/docs/id/plugins/conversations.md
  site/docs/plugins/conversations.md
  site/docs/zh/plugins/conversations.md
Labels: :es: ES, :cn: ZH, :indonesia: ID

#526 Fix typo
  site/docs/plugins/conversations.md
Labels: not translatable

#525 Adjust time to translate in guide
  TRANSLATING.md
Labels: not translatable, chore

#531 Undo Spanish translations of the code
  site/docs/es/guide/filter-queries.md
Labels: not translatable, :es: ES, hacktoberfest-accepted

#521 feat: add bot feats
  site/docs/.vuepress/config.ts
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID

#514 Add a note about the importance of correct combination of context flavors
  site/docs/es/guide/context.md
  site/docs/guide/context.md
  site/docs/id/guide/context.md
  site/docs/zh/guide/context.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID

#515 Document missing sync APIs on Deno Deploy
  site/docs/es/plugins/i18n.md
  site/docs/id/plugins/i18n.md
  site/docs/plugins/i18n.md
  site/docs/zh/plugins/i18n.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID
