Repository grammyjs/website, pull requests merged in 2022-09, with the labels that each got.

#492 Include deno.land/std in current-versions plugin
  site/docs/.vuepress/plugins/current-versions/build-index.ts
  site/docs/es/hosting/deno-deploy.md
  site/docs/es/hosting/supabase.md
  site/docs/hosting/deno-deploy.md
  site/docs/hosting/supabase.md
  site/docs/zh/hosting/deno-deploy.md
  site/docs/zh/hosting/supabase.md
Labels: not translatable

#480 Indonesian translations
  notifier/labels.json
  site/docs/.vuepress/config.ts
  site/docs/.vuepress/styles/index.scss
  site/docs/id/README.md
  site/docs/id/advanced/README.md
  site/docs/id/advanced/deployment.md
  site/docs/id/advanced/flood.md
  site/docs/id/advanced/middleware.md
  site/docs/id/advanced/proxy.md
  site/docs/id/advanced/reliability.md
  site/docs/id/advanced/scaling.md
  site/docs/id/advanced/structuring.md
  site/docs/id/advanced/transformers.md
  site/docs/id/demo/README.md
  site/docs/id/demo/examples.md
  site/docs/id/guide/README.md
  site/docs/id/guide/api.md
  site/docs/id/guide/basics.md
  site/docs/id/guide/commands.md
  site/docs/id/guide/context.md
  site/docs/id/guide/deployment-types.md
  site/docs/id/guide/errors.md
  site/docs/id/guide/files.md
  site/docs/id/guide/filter-queries.md
  site/docs/id/guide/games.md
  site/docs/id/guide/getting-started.md
  site/docs/id/guide/inline-queries.md
  site/docs/id/guide/introduction.md
  site/docs/id/guide/middleware.md
  site/docs/id/hosting/comparison.md
  site/docs/id/hosting/deno-deploy.md
  site/docs/id/hosting/gcf.md
  site/docs/id/hosting/heroku.md
  site/docs/id/hosting/supabase.md
  site/docs/id/hosting/vps.md
  site/docs/id/plugins/README.md
  site/docs/id/plugins/auto-retry.md
  site/docs/id/plugins/autoquote.md
  site/docs/id/plugins/command-filter.md
  site/docs/id/plugins/console-time.md
  site/docs/id/plugins/conversations.md
  site/docs/id/plugins/emoji.md
  site/docs/id/plugins/files.md
  site/docs/id/plugins/fluent.md
  site/docs/id/plugins/guide.md
  site/docs/id/plugins/hydrate.md
  site/docs/id/plugins/i18n.md
  site/docs/id/plugins/keyboard.md
  site/docs/id/plugins/menu.md
  site/docs/id/plugins/middlewares.md
  site/docs/id/plugins/parse-mode.md
  site/docs/id/plugins/ratelimiter.md
  site/docs/id/plugins/router.md
  site/docs/id/plugins/runner.md
  site/docs/id/plugins/session.md
  site/docs/id/plugins/stateless-question.md
  site/docs/id/plugins/transformer-throttler.md
  site/docs/id/resources/about.md
  site/docs/id/resources/comparison.md
  site/docs/id/resources/faq.md
Labels: :indonesia: ID

#494 Add missing parens
  site/docs/id/guide/getting-started.md
Labels: typo, not translatable, :indonesia: ID

#493 Sync #491 with Indonesian
  site/docs/id/hosting/deno-deploy.md
Labels: :indonesia: ID

#496 Sync #492 with Indonesian
  site/docs/id/hosting/deno-deploy.md
  site/docs/id/hosting/supabase.md
Labels: :indonesia: ID

#499 Update dependencies to fix vulnerabilities
  site/package-lock.json
  site/package.json
Labels: not translatable, chore

#503 Make the `ratelimiter` name casing consistent
  site/docs/.vuepress/public/ratelimiter-role.png
  site/docs/es/plugins/ratelimiter.md
  site/docs/id/plugins/ratelimiter.md
  site/docs/plugins/ratelimiter.md
  site/docs/zh/plugins/ratelimiter.md
Labels: typo, :es: ES, :cn: ZH, :indonesia: ID

#490 Translate #489
  site/docs/es/README.md
  site/docs/id/README.md
  site/docs/zh/README.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID

#431 Document I18n 1.0
  site/docs/.vuepress/config.ts
  site/docs/.vuepress/plugins/current-versions/modules.json
  site/docs/es/plugins/fluent.md
  site/docs/es/plugins/i18n.md
  site/docs/id/plugins/fluent.md
  site/docs/id/plugins/i18n.md
  site/docs/plugins/fluent.md
  site/docs/plugins/i18n.md
  site/docs/zh/plugins/fluent.md
  site/docs/zh/plugins/i18n.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID

#509 Fix typo on Spanish navigation menu
  site/docs/.vuepress/config.ts
Labels: typo, not translatable, :es: ES

#510 Add MyContext to I18n
  site/docs/es/plugins/i18n.md
  site/docs/id/plugins/i18n.md
  site/docs/plugins/i18n.md
  site/docs/zh/plugins/i18n.md
Labels: not translatable
