Repository grammyjs/website, pull requests merged in 2023-08, with the labels that each got.

#837 Add tutorial for Cloudflare Workers with Deno (#754)
  site/docs/.vitepress/configs/locales/en.ts
  site/docs/.vitepress/configs/locales/es.ts
  site/docs/.vitepress/configs/locales/id.ts
  site/docs/.vitepress/configs/locales/uk.ts
  site/docs/.vitepress/configs/locales/zh.ts
  site/docs/es/hosting/cloudflare-workers-nodejs.md
  site/docs/es/hosting/cloudflare-workers.md
  site/docs/hosting/cloudflare-workers-nodejs.md
  site/docs/hosting/cloudflare-workers.md
  site/docs/id/hosting/cloudflare-workers-nodejs.md
  site/docs/id/hosting/cloudflare-workers.md
  site/docs/uk/hosting/cloudflare-workers-nodejs.md
  site/docs/uk/hosting/cloudflare-workers.md
  site/docs/zh/hosting/cloudflare-workers-nodejs.md
  site/docs/zh/hosting/cloudflare-workers.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#851 Translate missed portions
  site/docs/.vitepress/configs/es.ts
  site/docs/.vitepress/configs/uk.ts
  site/docs/.vitepress/configs/zh.ts
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#883 [Chinese] Fix format
  site/docs/zh/hosting/cloudflare-workers.md
Labels: not translatable, :cn: ZH

#885 [Portuguese] Translate README.md
  site/docs/pt/README.md
Labels: not translatable, 🇧🇷 PT

#871 Update link checker
  .gitignore
  deno.jsonc
Labels: not translatable, chore

#890 Fix task
  deno.jsonc
Labels: not translatable

#892 Fix link
  site/docs/es/guide/deployment-types.md
  site/docs/guide/deployment-types.md
  site/docs/id/guide/deployment-types.md
  site/docs/id/hosting/cloudflare-workers.md
  site/docs/uk/guide/deployment-types.md
  site/docs/zh/guide/deployment-types.md
Labels: not translatable, :indonesia: ID

#891 Change light mode background
  site/docs/.vitepress/theme/style/_vars.scss
Labels: not translatable

#893 Fix typo
  site/docs/advanced/flood.md
Labels: typo, not translatable

#898 [Portuguese] Translate guide/basics.md
  site/docs/pt/guide/basics.md
Labels: not translatable, :brazil: PT

#901 [Portuguese] Translate guide/api.md
  site/docs/pt/guide/api.md
Labels: not translatable, :brazil: PT

#900 Improve consistency
  site/docs/hosting/deno-deploy.md
  site/docs/hosting/fly.md
Labels: not translatable

#902 Update to Bot API 6.8
  site/docs/README.md
Labels: ready for translation, time-sensitive

#903 Don’t check language labels if the time-sensitive label is added
  .github/workflows/translation-guard.yml
Labels: not translatable

#888 Add Cyclic hosting guide
  site/docs/.vitepress/configs/locales/en.ts
  site/docs/hosting/comparison.md
  site/docs/hosting/cyclic.md
Labels: not translatable

#899 Sessions are not external
  site/docs/es/plugins/conversations.md
  site/docs/id/plugins/conversations.md
  site/docs/plugins/conversations.md
  site/docs/uk/plugins/conversations.md
  site/docs/zh/plugins/conversations.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#842 Fix Missing Chinese Translation in Code
  site/docs/zh/plugins/conversations.md
Labels: not translatable, :cn: ZH

#904 Translate #902
  site/docs/es/README.md
  site/docs/id/README.md
  site/docs/uk/README.md
  site/docs/zh/README.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#909 [Ukrainian] Improve menu ID
  site/docs/uk/plugins/menu.md
Labels: typo, not translatable, :ukraine: UK
