Repository grammyjs/website, pull requests merged in 2023-02, with the labels that each got.

#591 fix: plugin not plugins
  site/docs/plugins/conversations.md
Labels: typo, not translatable

#592 fix: requests not request
  site/docs/hosting/comparison.md
Labels: not translatable

#595 fix: verbs are uppercase in titles
  site/docs/hosting/comparison.md
Labels: typo, not translatable

#588 feat(notifier): add ability to contribute to the website by uploading patch files
  notifier/deno.lock
  notifier/env.ts
  notifier/import_map.json
  notifier/main.ts
  notifier/utils.ts
Labels: not translatable

#598 refactor(notifier): use MongoDB instead of Supabase
  notifier/db.ts
  notifier/deno.json
  notifier/deno.lock
  notifier/env.ts
  notifier/import_map.json
  notifier/main.ts
Labels: not translatable

#599 chore: don’t use `deno.json` as import map since Deno Deploy doesn’t support it
  notifier/deno.json
  notifier/import_map.json
Labels: not translatable

#600 fix(notifier): don’t slice the signature header
  notifier/utils.ts
Labels: not translatable

#601 fix(notifier): correct the bot token path
  notifier/main.ts
Labels: not translatable

#602 fix(notifier): correct the Telegram webhook path’s method
  notifier/main.ts
Labels: not translatable

#603 fix(notifier): leave more and more problems in the dust
  notifier/main.ts
Labels: not translatable

#605 fix(notifier): serious logic issues with the file proxying thing
  notifier/main.ts
Labels: not translatable

#606 Improve consistency of code block names
  README.md
  site/docs/es/guide/getting-started.md
  site/docs/es/hosting/deno-deploy.md
  site/docs/es/hosting/heroku.md
  site/docs/es/hosting/vps.md
  site/docs/es/plugins/fluent.md
  site/docs/es/plugins/middlewares.md
  site/docs/guide/getting-started.md
  site/docs/hosting/deno-deploy.md
  site/docs/hosting/heroku.md
  site/docs/hosting/vps.md
  site/docs/id/guide/getting-started.md
  site/docs/id/hosting/deno-deploy.md
  site/docs/id/hosting/heroku.md
  site/docs/id/hosting/vps.md
  site/docs/id/plugins/fluent.md
  site/docs/id/plugins/middlewares.md
  site/docs/plugins/fluent.md
  site/docs/plugins/middlewares.md
Labels: not translatable

#584 Replace chat type checks with bot.chatType and ctx.hasChatType
  site/docs/es/guide/filter-queries.md
  site/docs/es/plugins/ratelimiter.md
  site/docs/guide/filter-queries.md
  site/docs/id/guide/filter-queries.md
  site/docs/id/plugins/ratelimiter.md
  site/docs/plugins/ratelimiter.md
Labels: not translatable

#607 Disable line numbers wherever unnecessary
  site/docs/es/hosting/deno-deploy.md
  site/docs/hosting/deno-deploy.md
  site/docs/id/hosting/deno-deploy.md
Labels: not translatable

#608 Replace VSCode with VS Code
  README.md
  site/docs/es/guide/introduction.md
  site/docs/es/resources/comparison.md
  site/docs/guide/introduction.md
  site/docs/id/guide/introduction.md
  site/docs/id/resources/comparison.md
  site/docs/resources/comparison.md
Labels: not translatable

#610 Correctly write Stack Overflow
  site/docs/es/guide/introduction.md
  site/docs/guide/introduction.md
  site/docs/id/guide/introduction.md
Labels: not translatable

#594 Fix incorrect statement about Deno Deploy file system
  site/docs/es/hosting/deno-deploy.md
  site/docs/hosting/deno-deploy.md
  site/docs/id/hosting/deno-deploy.md
Labels: ready for translation, :es: ES, :indonesia: ID

#589 Create FAQ entry about methods and parameters
  site/docs/es/resources/faq.md
  site/docs/id/resources/faq.md
  site/docs/resources/faq.md
Labels: ready for translation, :es: ES, :indonesia: ID

#590 feat: support Bot API 6.5
  site/docs/README.md
  site/docs/es/README.md
  site/docs/es/plugins/keyboard.md
  site/docs/id/README.md
  site/docs/id/plugins/keyboard.md
  site/docs/plugins/keyboard.md
Labels: ready for translation, :es: ES, :indonesia: ID

#597 Explain how to setup a development environment
  site/docs/es/guide/getting-started.md
  site/docs/es/guide/introduction.md
  site/docs/guide/getting-started.md
  site/docs/guide/introduction.md
  site/docs/id/guide/getting-started.md
  site/docs/id/guide/introduction.md
Labels: ready for translation, :es: ES, :indonesia: ID

#613 Repair broken link
  site/docs/es/resources/faq.md
Labels: typo, not translatable, :es: ES

#609 Change fonts
  site/docs/.vuepress/public/fonts/red-hat-display-v14-latin-ext_latin-700.woff2
  site/docs/.vuepress/public/fonts/red-hat-text-v13-latin-ext_latin-600.woff2
  site/docs/.vuepress/public/fonts/red-hat-text-v13-latin-ext_latin-italic.woff2
  site/docs/.vuepress/public/fonts/red-hat-text-v13-latin-ext_latin-regular.woff2
  site/docs/.vuepress/public/fonts/source-code-pro-v22-latin-regular.woff2
  site/docs/.vuepress/styles/_fonts.scss
  site/docs/.vuepress/styles/index.scss
Labels: not translatable

#614 Configure the Cache-Control header for fonts
  .github/workflows/build.yml
  site/netlify.toml
Labels: not translatable

#615 feat: use Deno for sitemap generation
  site/package.json
Labels: not translatable, chore

#616 Trigger build on workflow_dispatch
  .github/workflows/build.yml
Labels: not translatable

#612 Customize and limit selection
  site/docs/.vuepress/styles/_selection.scss
  site/docs/.vuepress/styles/index.scss
  site/docs/es/guide/README.md
  site/docs/guide/README.md
  site/docs/id/guide/README.md
Labels: not translatable

#617 Use Cache-Control for images
  site/docs/.vuepress/config.ts
  site/docs/.vuepress/public/images/Y.png
  site/docs/.vuepress/public/images/filter-query-search.png
  site/docs/.vuepress/public/images/grammY.png
  site/docs/.vuepress/public/images/inline-keyboard-example-1.jpeg
  site/docs/.vuepress/public/images/inline-keyboard-example-1.webp
  site/docs/.vuepress/public/images/inline-keyboard-example-2.jpeg
  site/docs/.vuepress/public/images/inline-keyboard-example-2.webp
  site/docs/.vuepress/public/images/inline-keyboard-example-3.jpeg
  site/docs/.vuepress/public/images/inline-keyboard-example-3.webp
  site/docs/.vuepress/public/images/keyboard-example-1.jpeg
  site/docs/.vuepress/public/images/keyboard-example-1.webp
  site/docs/.vuepress/public/images/keyboard-example-2.jpeg
  site/docs/.vuepress/public/images/keyboard-example-2.webp
  site/docs/.vuepress/public/images/keyboard-example-3.jpeg
  site/docs/.vuepress/public/images/keyboard-example-3.webp
  site/docs/.vuepress/public/images/ratelimiter-role.png
  site/docs/README.md
  site/docs/es/README.md
  site/docs/es/guide/files.md
  site/docs/es/guide/filter-queries.md
  site/docs/es/plugins/keyboard.md
  site/docs/es/plugins/ratelimiter.md
  site/docs/guide/files.md
  site/docs/guide/filter-queries.md
  site/docs/id/README.md
  site/docs/id/guide/files.md
  site/docs/id/guide/filter-queries.md
  site/docs/id/plugins/keyboard.md
  site/docs/id/plugins/ratelimiter.md
  site/docs/plugins/keyboard.md
  site/docs/plugins/ratelimiter.md
  site/netlify.toml
  site/package-lock.json
Labels: not translatable

#619 Fix broken imports
  site/docs/es/guide/README.md
  site/docs/guide/README.md
  site/docs/id/guide/README.md
Labels: not translatable

#618 Use custom fonts for Cyrillic
  site/docs/.vuepress/public/fonts/noto-sans-display-v20-cyrillic-ext_cyrillic-700.woff2
  site/docs/.vuepress/public/fonts/noto-sans-v27-cyrillic-ext_cyrillic-600.woff2
  site/docs/.vuepress/public/fonts/noto-sans-v27-cyrillic-ext_cyrillic-italic.woff2
  site/docs/.vuepress/public/fonts/noto-sans-v27-cyrillic-ext_cyrillic-regular.woff2
  site/docs/.vuepress/styles/_fonts.scss
Labels: not translatable

#621 Do not make people use their forks for translations
  TRANSLATING.md
Labels: not translatable

#624 RU: fix format of files by removing TODO prefixes
  site/docs/ru/advanced/README.md
  site/docs/ru/advanced/deployment.md
  site/docs/ru/advanced/flood.md
  site/docs/ru/advanced/middleware.md
  site/docs/ru/advanced/proxy.md
  site/docs/ru/advanced/reliability.md
  site/docs/ru/advanced/scaling.md
  site/docs/ru/advanced/structuring.md
  site/docs/ru/advanced/transformers.md
  site/docs/ru/demo/README.md
  site/docs/ru/demo/examples.md
  site/docs/ru/guide/README.md
  site/docs/ru/guide/api.md
  site/docs/ru/guide/basics.md
  site/docs/ru/guide/commands.md
  site/docs/ru/guide/context.md
  site/docs/ru/guide/deployment-types.md
  site/docs/ru/guide/errors.md
  site/docs/ru/guide/files.md
  site/docs/ru/guide/filter-queries.md
  site/docs/ru/guide/games.md
  site/docs/ru/guide/getting-started.md
  site/docs/ru/guide/inline-queries.md
  site/docs/ru/guide/introduction.md
  site/docs/ru/guide/middleware.md
  site/docs/ru/hosting/comparison.md
  site/docs/ru/hosting/deno-deploy.md
  site/docs/ru/hosting/fly.md
  site/docs/ru/hosting/gcf.md
  site/docs/ru/hosting/heroku.md
  site/docs/ru/hosting/supabase.md
  site/docs/ru/hosting/vercel.md
  site/docs/ru/hosting/vps.md
  site/docs/ru/plugins/README.md
  site/docs/ru/plugins/auto-retry.md
  site/docs/ru/plugins/autoquote.md
  site/docs/ru/plugins/command-filter.md
  site/docs/ru/plugins/console-time.md
  site/docs/ru/plugins/conversations.md
  site/docs/ru/plugins/emoji.md
  site/docs/ru/plugins/files.md
  site/docs/ru/plugins/fluent.md
  site/docs/ru/plugins/guide.md
  site/docs/ru/plugins/hydrate.md
  site/docs/ru/plugins/i18n.md
  site/docs/ru/plugins/keyboard.md
  site/docs/ru/plugins/menu.md
  site/docs/ru/plugins/middlewares.md
  site/docs/ru/plugins/parse-mode.md
  site/docs/ru/plugins/ratelimiter.md
  site/docs/ru/plugins/router.md
  site/docs/ru/plugins/runner.md
  site/docs/ru/plugins/session.md
  site/docs/ru/plugins/stateless-question.md
  site/docs/ru/plugins/transformer-throttler.md
  site/docs/ru/resources/about.md
  site/docs/ru/resources/comparison.md
  site/docs/ru/resources/faq.md
Labels: not translatable

#625 Fix dates and links of the last Bot API update
  site/docs/README.md
  site/docs/es/README.md
  site/docs/id/README.md
Labels: not translatable

#627 Were, not was
  site/docs/plugins/conversations.md
Labels: typo, not translatable

#626 Mention the simpler /types setup first
  site/docs/es/guide/api.md
  site/docs/guide/api.md
  site/docs/id/guide/api.md
Labels: ready for translation, :es: ES, :indonesia: ID

#629 Sync #627 with Indonesian
  site/docs/id/plugins/conversations.md
Labels: not translatable, :indonesia: ID

#559 Inform about silent supergroup migrations
  site/docs/es/plugins/session.md
  site/docs/id/plugins/session.md
  site/docs/plugins/session.md
Labels: ready for translation, :es: ES, :indonesia: ID

#630 [Spanish] Translate missed sentences
  site/docs/es/guide/api.md
Labels: not translatable, :es: ES
