Repository grammyjs/website, pull requests merged in 2023-06, with the labels that each got.

#785 Fix link in #777
  site/docs/es/hosting/comparison.md
  site/docs/hosting/comparison.md
  site/docs/id/hosting/comparison.md
  site/docs/zh/hosting/comparison.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#779 Set font-display to swap
  site/docs/.vuepress/styles/_fonts.scss
Labels: not translatable

#792 Rename format.yml to check.yml and add link checking job
  .github/workflows/check.yml
  .github/workflows/format.yml
Labels: not translatable

#789 Add unused but explanatory async
  site/docs/advanced/structuring.md
  site/docs/advanced/transformers.md
  site/docs/es/advanced/structuring.md
  site/docs/es/advanced/transformers.md
  site/docs/es/guide/basics.md
  site/docs/es/guide/commands.md
  site/docs/es/guide/context.md
  site/docs/es/guide/filter-queries.md
  site/docs/es/guide/games.md
  site/docs/es/plugins/router.md
  site/docs/es/plugins/session.md
  site/docs/es/plugins/stateless-question.md
  site/docs/guide/basics.md
  site/docs/guide/commands.md
  site/docs/guide/context.md
  site/docs/guide/filter-queries.md
  site/docs/guide/games.md
  site/docs/id/advanced/structuring.md
  site/docs/id/advanced/transformers.md
  site/docs/id/guide/basics.md
  site/docs/id/guide/commands.md
  site/docs/id/guide/context.md
  site/docs/id/guide/filter-queries.md
  site/docs/id/guide/games.md
  site/docs/id/plugins/router.md
  site/docs/id/plugins/session.md
  site/docs/id/plugins/stateless-question.md
  site/docs/plugins/router.md
  site/docs/plugins/session.md
  site/docs/plugins/stateless-question.md
  site/docs/uk/advanced/structuring.md
  site/docs/uk/advanced/transformers.md
  site/docs/uk/guide/basics.md
  site/docs/uk/guide/commands.md
  site/docs/uk/guide/context.md
  site/docs/uk/guide/filter-queries.md
  site/docs/uk/guide/games.md
  site/docs/uk/guide/middleware.md
  site/docs/uk/plugins/router.md
  site/docs/uk/plugins/session.md
  site/docs/uk/plugins/stateless-question.md
  site/docs/zh/advanced/structuring.md
  site/docs/zh/advanced/transformers.md
  site/docs/zh/guide/basics.md
  site/docs/zh/guide/commands.md
  site/docs/zh/guide/context.md
  site/docs/zh/guide/filter-queries.md
  site/docs/zh/guide/games.md
  site/docs/zh/plugins/router.md
  site/docs/zh/plugins/session.md
  site/docs/zh/plugins/stateless-question.md
Labels: not translatable

#793 Separate link checker job
  .github/workflows/check.yml
Labels: not translatable

#797 fix: update ioredis repo link
  site/docs/es/plugins/ratelimiter.md
  site/docs/id/plugins/ratelimiter.md
  site/docs/plugins/ratelimiter.md
  site/docs/uk/plugins/ratelimiter.md
  site/docs/zh/plugins/ratelimiter.md
Labels: not translatable

#799 Disable prefetch
  site/docs/.vuepress/config.ts
Labels: not translatable

#802 Make link-checker easier to run locally
  .github/workflows/check.yml
  .vscode/settings.json
  deno.jsonc
Labels: not translatable

#804 Improve and make code blocks syntax consistent
  site/docs/es/hosting/deno-deploy.md
  site/docs/es/hosting/firebase.md
  site/docs/es/hosting/fly.md
  site/docs/es/hosting/heroku.md
  site/docs/es/hosting/supabase.md
  site/docs/es/hosting/vercel.md
  site/docs/es/plugins/console-time.md
  site/docs/es/plugins/fluent.md
  site/docs/es/plugins/i18n.md
  site/docs/es/plugins/session.md
  site/docs/hosting/deno-deploy.md
  site/docs/hosting/firebase.md
  site/docs/hosting/fly.md
  site/docs/hosting/heroku.md
  site/docs/hosting/supabase.md
  site/docs/hosting/vercel.md
  site/docs/id/hosting/deno-deploy.md
  site/docs/id/hosting/firebase.md
  site/docs/id/hosting/fly.md
  site/docs/id/hosting/heroku.md
  site/docs/id/hosting/supabase.md
  site/docs/id/hosting/vercel.md
  site/docs/id/plugins/console-time.md
  site/docs/id/plugins/fluent.md
  site/docs/id/plugins/i18n.md
  site/docs/id/plugins/session.md
  site/docs/plugins/console-time.md
  site/docs/plugins/fluent.md
  site/docs/plugins/i18n.md
  site/docs/plugins/session.md
  site/docs/uk/hosting/deno-deploy.md
  site/docs/uk/hosting/firebase.md
  site/docs/uk/hosting/fly.md
  site/docs/uk/hosting/heroku.md
  site/docs/uk/hosting/supabase.md
  site/docs/uk/hosting/vercel.md
  site/docs/uk/plugins/console-time.md
  site/docs/uk/plugins/fluent.md
  site/docs/uk/plugins/i18n.md
  site/docs/uk/plugins/session.md
  site/docs/zh/hosting/deno-deploy.md
  site/docs/zh/hosting/firebase.md
  site/docs/zh/hosting/fly.md
  site/docs/zh/hosting/heroku.md
  site/docs/zh/hosting/supabase.md
  site/docs/zh/hosting/vercel.md
  site/docs/zh/plugins/console-time.md
  site/docs/zh/plugins/fluent.md
  site/docs/zh/plugins/i18n.md
  site/docs/zh/plugins/session.md
Labels: not translatable

#811 Remove outdated notice from Translation Guide
  TRANSLATING.md
Labels: not translatable

#812 [Ukrainian] Correct of the translation of “free”
  site/docs/uk/resources/about.md
Labels: not translatable, :ukraine: UK

#813 Fix code groups
  site/docs/uk/hosting/heroku.md
  site/docs/zh/hosting/heroku.md
Labels: not translatable

#816 [Ukrainian] Fix typo
  site/docs/.vuepress/configs/uk.ts
Labels: not translatable, :ukraine: UK

#788 Disambiguate type exports
  site/docs/es/guide/api.md
  site/docs/guide/api.md
  site/docs/id/guide/api.md
  site/docs/uk/guide/api.md
  site/docs/zh/guide/api.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#819 Replace deno-bin with me
  site/package-lock.json
  site/package.json
Labels: not translatable

#818 Update Contribution Guide
  CONTRIBUTING.md
Labels: not translatable

#820 Update package.json
  site/package-lock.json
  site/package.json
Labels: not translatable

#823 Update TRANSLATING.md
  TRANSLATING.md
Labels: not translatable

#803 Constructed download URL? Really?
  site/docs/es/guide/files.md
  site/docs/guide/files.md
  site/docs/id/guide/files.md
  site/docs/uk/guide/files.md
  site/docs/zh/guide/files.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#822 Revert "Replace deno-bin with me"
  site/package-lock.json
  site/package.json
Labels: not translatable

#794 we all know they do
  site/docs/es/guide/deployment-types.md
  site/docs/guide/deployment-types.md
  site/docs/id/guide/deployment-types.md
  site/docs/uk/guide/deployment-types.md
  site/docs/zh/guide/deployment-types.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#787 Update Deta information
  site/docs/es/hosting/comparison.md
  site/docs/hosting/comparison.md
  site/docs/id/hosting/comparison.md
  site/docs/uk/hosting/comparison.md
  site/docs/zh/hosting/comparison.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#807 Document InputFile supplier functions
  site/docs/es/guide/files.md
  site/docs/guide/files.md
  site/docs/id/guide/files.md
  site/docs/uk/guide/files.md
  site/docs/zh/guide/files.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#827 Update Deno Deploy Pricing (#825)
  site/docs/es/hosting/comparison.md
  site/docs/hosting/comparison.md
  site/docs/id/hosting/comparison.md
  site/docs/uk/hosting/comparison.md
  site/docs/zh/hosting/comparison.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#829 Fix links
  site/docs/es/hosting/comparison.md
  site/docs/hosting/comparison.md
  site/docs/id/hosting/comparison.md
  site/docs/zh/hosting/comparison.md
Labels: not translatable

#809 Document upcoming media group plugin
  site/docs/.vuepress/configs/en.ts
  site/docs/.vuepress/configs/es.ts
  site/docs/.vuepress/configs/id.ts
  site/docs/.vuepress/configs/uk.ts
  site/docs/.vuepress/configs/zh.ts
  site/docs/es/plugins/media-group.md
  site/docs/id/plugins/media-group.md
  site/docs/plugins/media-group.md
  site/docs/uk/plugins/media-group.md
  site/docs/zh/plugins/media-group.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#821 Mention auto-retry plugin in deployment checklist
  site/docs/advanced/deployment.md
  site/docs/es/advanced/deployment.md
  site/docs/es/plugins/auto-retry.md
  site/docs/es/plugins/transformer-throttler.md
  site/docs/id/advanced/deployment.md
  site/docs/id/plugins/auto-retry.md
  site/docs/id/plugins/keyboard.md
  site/docs/id/plugins/session.md
  site/docs/id/plugins/transformer-throttler.md
  site/docs/plugins/auto-retry.md
  site/docs/plugins/transformer-throttler.md
  site/docs/uk/advanced/deployment.md
  site/docs/uk/plugins/auto-retry.md
  site/docs/uk/plugins/transformer-throttler.md
  site/docs/zh/advanced/deployment.md
  site/docs/zh/plugins/auto-retry.md
  site/docs/zh/plugins/transformer-throttler.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#831 We handled billions of updates, not just ~100M
  site/docs/README.md
  site/docs/es/README.md
  site/docs/id/README.md
  site/docs/uk/README.md
  site/docs/zh/README.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#808 Document new inline query plugin
  site/docs/.vuepress/configs/en.ts
  site/docs/.vuepress/configs/es.ts
  site/docs/.vuepress/configs/id.ts
  site/docs/.vuepress/configs/uk.ts
  site/docs/.vuepress/configs/zh.ts
  site/docs/es/guide/errors.md
  site/docs/es/guide/files.md
  site/docs/es/guide/inline-queries.md
  site/docs/es/plugins/inline-query.md
  site/docs/es/plugins/keyboard.md
  site/docs/guide/errors.md
  site/docs/guide/files.md
  site/docs/guide/inline-queries.md
  site/docs/id/guide/errors.md
  site/docs/id/guide/files.md
  site/docs/id/guide/inline-queries.md
  site/docs/id/plugins/inline-query.md
  site/docs/id/plugins/keyboard.md
  site/docs/plugins/inline-query.md
  site/docs/plugins/keyboard.md
  site/docs/uk/guide/errors.md
  site/docs/uk/guide/files.md
  site/docs/uk/guide/filter-queries.md
  site/docs/uk/plugins/inline-query.md
  site/docs/uk/plugins/keyboard.md
  site/docs/zh/guide/errors.md
  site/docs/zh/guide/files.md
  site/docs/zh/guide/inline-queries.md
  site/docs/zh/plugins/inline-query.md
  site/docs/zh/plugins/keyboard.md
  site/netlify.toml
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#835 [Ukrainian] Restore guide/filter-queries
  site/docs/uk/guide/filter-queries.md
  site/docs/uk/guide/inline-queries.md
Labels: not translatable, :ukraine: UK

#800 Rewrite Scaling Up IV
  site/docs/.vuepress/configs/id.ts
  site/docs/advanced/flood.md
  site/docs/es/advanced/flood.md
  site/docs/id/advanced/flood.md
  site/docs/uk/advanced/flood.md
  site/docs/zh/advanced/flood.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#754 Add tutorial for Cloudflare Workers with Deno
  site/docs/.vuepress/configs/en.ts
  site/docs/hosting/cloudflare-workers-deno.md
  site/docs/hosting/cloudflare-workers.md
Labels: not translatable

#828 Unrecommend using menus and conversations together
  site/docs/es/plugins/conversations.md
  site/docs/id/plugins/conversations.md
  site/docs/plugins/conversations.md
  site/docs/uk/plugins/conversations.md
  site/docs/zh/plugins/conversations.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#838 Fix broken anchor
  site/docs/uk/advanced/flood.md
Labels: not translatable

#839 Minor improvements
  site/docs/es/advanced/flood.md
  site/docs/es/guide/getting-started.md
  site/docs/es/guide/introduction.md
  site/docs/es/hosting/heroku.md
  site/docs/es/plugins/inline-query.md
  site/docs/guide/introduction.md
  site/docs/hosting/heroku.md
  site/docs/id/hosting/heroku.md
  site/docs/uk/guide/introduction.md
  site/docs/uk/hosting/heroku.md
  site/docs/zh/guide/introduction.md
  site/docs/zh/hosting/heroku.md
Labels: not translatable

#840 [Spanish] Resolve redirecting link
  site/docs/es/guide/introduction.md
Labels: not translatable, :es: ES

#841 Fix links
  site/docs/es/plugins/guide.md
  site/docs/guide/getting-started.md
  site/docs/guide/introduction.md
  site/docs/id/guide/getting-started.md
  site/docs/id/guide/introduction.md
  site/docs/id/plugins/guide.md
  site/docs/plugins/guide.md
  site/docs/uk/guide/getting-started.md
  site/docs/uk/guide/introduction.md
  site/docs/uk/plugins/guide.md
  site/docs/zh/guide/getting-started.md
  site/docs/zh/guide/introduction.md
  site/docs/zh/plugins/guide.md
Labels: not translatable
