Repository grammyjs/website, pull requests merged in 2023-05, with the labels that each got.

#771 Replace Node with Node.js
  site/docs/advanced/reliability.md
  site/docs/es/advanced/reliability.md
  site/docs/zh/advanced/reliability.md
Labels: not translatable, :cn: ZH, :indonesia: ID

#773 Typo Fix
  site/docs/advanced/middleware.md
Labels: not translatable

#775 Minor fixes and improvements
  deno.json
  site/docs/.vuepress/configs/en.ts
  site/docs/advanced/scaling.md
  site/docs/es/advanced/scaling.md
  site/docs/es/hosting/comparison.md
  site/docs/guide/introduction.md
  site/docs/hosting/comparison.md
  site/docs/id/advanced/scaling.md
  site/docs/zh/advanced/scaling.md
  site/docs/zh/guide/getting-started.md
  site/docs/zh/hosting/comparison.md
  site/docs/zh/plugins/i18n.md
Labels: typo, not translatable, chore

#768 Translate #767
  site/docs/README.md
  site/docs/es/README.md
  site/docs/es/plugins/keyboard.md
  site/docs/id/README.md
  site/docs/id/plugins/keyboard.md
  site/docs/zh/README.md
  site/docs/zh/plugins/keyboard.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID

#776 [Spanish] Update Bot API version to 6.7
  site/docs/es/README.md
Labels: not translatable, :es: ES

#764 Update details for Vercel
  site/docs/es/hosting/comparison.md
  site/docs/hosting/comparison.md
  site/docs/id/hosting/comparison.md
  site/docs/zh/hosting/comparison.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID

#780 [Ukrainian] Sync hosting comparison
  site/docs/uk/hosting/comparison.md
Labels: not translatable, 🇺🇦 UK

#782 Use Cyrillic variants of Source Code Pro
  site/docs/.vuepress/public/fonts/source-code-pro-v22-cyrillic_cyrillic-ext_latin_latin-ext-regular.woff2
  site/docs/.vuepress/public/fonts/source-code-pro-v22-latin-regular.woff2
  site/docs/.vuepress/styles/_fonts.scss
Labels: not translatable

#783 Configure font with variables
  site/docs/.vuepress/styles/_fonts.scss
  site/docs/.vuepress/styles/_vars.scss
Labels: not translatable

#784 Fix typo
  site/docs/advanced/scaling.md
Labels: not translatable
