Repository grammyjs/website, pull requests merged in 2023-07, with the labels that each got.

#844 Update Deno Binary
  site/package-lock.json
  site/package.json
Labels: not translatable, chore

#845 [Ukrainian] Fix typos
  site/docs/uk/advanced/transformers.md
  site/docs/uk/guide/context.md
Labels: not translatable, :ukraine: UK

#832 Update the plugin list
  site/docs/es/plugins/README.md
  site/docs/id/plugins/README.md
  site/docs/plugins/README.md
  site/docs/uk/plugins/README.md
  site/docs/zh/plugins/README.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#833 Add link reference for 429 errors
  site/docs/es/plugins/auto-retry.md
  site/docs/id/plugins/auto-retry.md
  site/docs/plugins/auto-retry.md
  site/docs/uk/plugins/auto-retry.md
  site/docs/zh/plugins/auto-retry.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#846 Sorry
  README.md
Labels: not translatable

#847 Revert "Sorry"
  README.md
Labels: not translatable

#850 Minor improvements
  site/docs/.vitepress/config.ts
  site/docs/.vitepress/configs/id.ts
  site/docs/.vitepress/theme/style/_normalize.scss
Labels: not translatable, chore

#854 Use system theme
  site/docs/.vitepress/config.ts
Labels: not translatable

#852 Exclude cache folder from deno fmt
  deno.jsonc
Labels: not translatable, chore

#862 Fix duplicate text
  site/docs/guide/deployment-types.md
  site/docs/id/guide/deployment-types.md
Labels: not translatable

#856 Add Y in SVG and fix typos
  logos/README.md
  logos/Y.svg
Labels: not translatable

#860 Fix external-link-icon margin
  site/docs/.vitepress/theme/style/_normalize.scss
Labels: not translatable, style

#857 Fix spacing
  site/docs/.vitepress/theme/style/_normalize.scss
  site/docs/README.md
  site/docs/es/README.md
  site/docs/id/README.md
  site/docs/uk/README.md
  site/docs/zh/README.md
Labels: not translatable, style

#865 Remove lost file
  .github/workflows-algolia.yml
Labels: not translatable, chore

#868 Fix punctuation
  site/docs/resources/about.md
Labels: not translatable

#873 Fix typo
  site/docs/plugins/runner.md
Labels: typo, not translatable

#874 Update code example
  site/docs/es/plugins/keyboard.md
  site/docs/id/plugins/keyboard.md
  site/docs/plugins/keyboard.md
  site/docs/uk/plugins/keyboard.md
  site/docs/zh/plugins/keyboard.md
Labels: typo

#879 [Indonesian] Fix typo
  site/docs/id/resources/comparison.md
Labels: typo, not translatable, :indonesia: ID

#861 Use Algolia search
  site/docs/.vitepress/config.ts
  site/docs/.vitepress/configs/algolia/crawler.js
  site/docs/.vitepress/configs/algolia/index.ts
  site/docs/.vitepress/configs/locales/en.ts
  site/docs/.vitepress/configs/locales/es.ts
  site/docs/.vitepress/configs/locales/id.ts
  site/docs/.vitepress/configs/locales/index.ts
  site/docs/.vitepress/configs/locales/main.ts
  site/docs/.vitepress/configs/locales/uk.ts
  site/docs/.vitepress/configs/locales/zh.ts
  site/docs/.vitepress/theme/layout/NotFound.vue
Labels: not translatable, chore

#864 Update taglines
  site/docs/README.md
  site/docs/es/README.md
  site/docs/id/README.md
  site/docs/uk/README.md
  site/docs/zh/README.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#853 Add ref
  site/docs/es/plugins/files.md
  site/docs/id/plugins/files.md
  site/docs/plugins/files.md
  site/docs/uk/plugins/files.md
  site/docs/zh/plugins/files.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#848 Fix title
  site/docs/es/plugins/inline-query.md
  site/docs/id/plugins/inline-query.md
  site/docs/plugins/inline-query.md
  site/docs/uk/plugins/inline-query.md
  site/docs/zh/plugins/inline-query.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#859 Display identicon when contributor has no avatar
  site/docs/.vitepress/components/ThankYou.vue
Labels: not translatable, style

#869 Improve payload limitation docs
  site/docs/es/plugins/menu.md
  site/docs/id/plugins/menu.md
  site/docs/plugins/menu.md
  site/docs/uk/plugins/menu.md
  site/docs/zh/plugins/menu.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#875 Add tagline
  site/docs/README.md
  site/docs/es/README.md
  site/docs/id/README.md
  site/docs/uk/README.md
  site/docs/zh/README.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#882 Fix code examples
  site/docs/es/hosting/fly.md
  site/docs/es/hosting/supabase.md
  site/docs/hosting/fly.md
  site/docs/hosting/supabase.md
  site/docs/id/hosting/fly.md
  site/docs/id/hosting/supabase.md
  site/docs/uk/hosting/fly.md
  site/docs/uk/hosting/supabase.md
  site/docs/zh/hosting/fly.md
  site/docs/zh/hosting/supabase.md
Labels: not translatable, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK
