Repository grammyjs/website, pull requests merged in 2023-12, with the labels that each got.

#955 Add missing Chinese translation
  site/docs/zh/advanced/structuring.md
Labels: not translatable, :cn: ZH

#963 Merge crawler configs
  algolia-crawler-config.ts
  site/docs/.vitepress/configs/algolia/crawler.ts
Labels: not translatable, chore

#965 Handle deleted accounts
  site/docs/.vitepress/components/ThankYou.vue
Labels: not translatable, chore

#966 Update Algolia config
  site/docs/.vitepress/configs/algolia/crawler.ts
Labels: not translatable

#959 Update dependencies and localize the 404 page
  deno.jsonc
  site/docs/.vitepress/components/NotFound.vue
  site/docs/.vitepress/config.ts
  site/docs/.vitepress/configs/algolia/index.ts
  site/docs/.vitepress/configs/locales/en.ts
  site/docs/.vitepress/configs/locales/es.ts
  site/docs/.vitepress/configs/locales/id.ts
  site/docs/.vitepress/configs/locales/index.ts
  site/docs/.vitepress/configs/locales/main.ts
  site/docs/.vitepress/configs/locales/uk.ts
  site/docs/.vitepress/configs/locales/zh.ts
  site/docs/.vitepress/deps/langs.ts
  site/docs/.vitepress/deps/shared.ts
  site/docs/.vitepress/deps/utils.ts
  site/docs/.vitepress/plugins/better-line-breaks/plugins.ts
  site/docs/.vitepress/plugins/index.ts
  site/docs/.vitepress/plugins/markdown.ts
  site/docs/.vitepress/shared/shiki-languages/ftl.tmLanguage.json
  site/docs/.vitepress/shared/shiki-languages/log.tmLanguage.json
  site/docs/.vitepress/shared/shiki-languages/plaintext.tmLanguage.json
  site/docs/.vitepress/shared/shiki-languages/procfile.tmLanguage.json
  site/docs/.vitepress/shared/syntaxes/plaintext.tmLanguage.json
  site/docs/.vitepress/shared/types.ts
  site/docs/.vitepress/theme/index.ts
  site/docs/.vitepress/theme/layout/Layout.vue
  site/docs/.vitepress/theme/layout/NotFound.vue
  site/docs/.vitepress/theme/style/_custom-block.scss
  site/docs/.vitepress/theme/style/_vars.scss
  site/docs/404.md
  site/docs/es/404.md
  site/docs/id/404.md
  site/docs/uk/404.md
  site/docs/zh/404.md
  site/netlify.toml
  site/package-lock.json
  site/package.json
  site/tsconfig.app.json
  site/tsconfig.json
  site/tsconfig.node.json
Labels: not translatable, chore

#967 Update faq.md
  site/docs/es/resources/faq.md
  site/docs/id/resources/faq.md
  site/docs/resources/faq.md
  site/docs/uk/resources/faq.md
  site/docs/zh/resources/faq.md
Labels: not translatable

#968 Fix typo
  site/docs/resources/faq.md
Labels: typo, not translatable

#969 Replace Red Hat and Noto Sans with Inter
  site/docs/.vitepress/theme/style/_fonts.scss
  site/docs/public/fonts/InterVariable-Italic.woff2
  site/docs/public/fonts/InterVariable.woff2
  site/docs/public/fonts/noto-sans-display-v20-cyrillic-ext_cyrillic-700.woff2
  site/docs/public/fonts/noto-sans-v27-cyrillic-ext_cyrillic-600.woff2
  site/docs/public/fonts/noto-sans-v27-cyrillic-ext_cyrillic-italic.woff2
  site/docs/public/fonts/noto-sans-v27-cyrillic-ext_cyrillic-regular.woff2
  site/docs/public/fonts/red-hat-display-v14-latin-ext_latin-700.woff2
  site/docs/public/fonts/red-hat-text-v13-latin-ext_latin-600.woff2
  site/docs/public/fonts/red-hat-text-v13-latin-ext_latin-italic.woff2
  site/docs/public/fonts/red-hat-text-v13-latin-ext_latin-regular.woff2
Labels: not translatable

#970 Apply Inter in missed places
  site/docs/.vitepress/theme/style/_vars.scss
Labels: not translatable

#971 Document changes for Bot API 7.0
  site/docs/.vitepress/configs/locales/en.ts
  site/docs/README.md
  site/docs/guide/basics.md
  site/docs/guide/context.md
  site/docs/guide/filter-queries.md
  site/docs/guide/reactions.md
  site/docs/plugins/autoquote.md
  site/docs/plugins/emoji.md
Labels: not translatable, time-sensitive

#975 Update copyright years
  site/docs/README.md
  site/docs/es/README.md
  site/docs/id/README.md
  site/docs/uk/README.md
  site/docs/zh/README.md
Labels: not translatable
