Repository grammyjs/website, pull requests merged in 2023-10, with the labels that each got.

#912 Update Bot API to 6.9
  site/docs/README.md
  site/docs/id/README.md
  site/docs/uk/README.md
Labels: :indonesia: ID, :ukraine: UK, time-sensitive

#915 Translate #912
  site/docs/es/README.md
  site/docs/zh/README.md
Labels: not translatable, :es: ES, :cn: ZH

#870 Never use empty lines around tips
  site/docs/es/advanced/deployment.md
  site/docs/es/guide/api.md
  site/docs/es/guide/commands.md
  site/docs/es/guide/context.md
  site/docs/es/guide/introduction.md
  site/docs/es/plugins/conversations.md
  site/docs/es/plugins/i18n.md
  site/docs/es/plugins/router.md
  site/docs/guide/api.md
  site/docs/guide/context.md
  site/docs/guide/introduction.md
  site/docs/id/guide/api.md
  site/docs/id/guide/context.md
  site/docs/id/guide/introduction.md
  site/docs/id/plugins/conversations.md
  site/docs/id/plugins/i18n.md
  site/docs/id/plugins/router.md
  site/docs/plugins/conversations.md
  site/docs/plugins/i18n.md
  site/docs/plugins/router.md
  site/docs/uk/guide/api.md
  site/docs/uk/guide/context.md
  site/docs/uk/guide/introduction.md
  site/docs/uk/plugins/conversations.md
  site/docs/uk/plugins/i18n.md
  site/docs/uk/plugins/router.md
  site/docs/zh/guide/api.md
  site/docs/zh/guide/introduction.md
  site/docs/zh/plugins/conversations.md
  site/docs/zh/plugins/i18n.md
Labels: not translatable

#916 Update import
  site/docs/es/hosting/cloudflare-workers-nodejs.md
  site/docs/hosting/cloudflare-workers-nodejs.md
  site/docs/id/hosting/cloudflare-workers-nodejs.md
  site/docs/uk/hosting/cloudflare-workers-nodejs.md
  site/docs/zh/hosting/cloudflare-workers-nodejs.md
Labels: not translatable

#919 Use global URL
  site/docs/es/guide/files.md
  site/docs/guide/files.md
  site/docs/id/guide/files.md
  site/docs/uk/guide/files.md
  site/docs/zh/guide/files.md
Labels: not translatable

#906 [Portuguese] translate context.md
  site/docs/pt/guide/README.md
  site/docs/pt/guide/context.md
  site/docs/pt/guide/getting-started.md
Labels: not translatable, :brazil: PT

#924 [Portuguese] translate filter-queries.md
  site/docs/pt/guide/filter-queries.md
Labels: not translatable

#929 Fix typo
  site/docs/es/guide/api.md
Labels: not translatable, :es: ES

#925 [Portuguese] translate middleware.md
  site/docs/pt/guide/middleware.md
Labels: not translatable

#930 Update links to examples
  site/docs/es/hosting/deno-deploy.md
  site/docs/es/hosting/supabase.md
  site/docs/hosting/deno-deploy.md
  site/docs/hosting/supabase.md
  site/docs/id/hosting/deno-deploy.md
  site/docs/id/hosting/supabase.md
  site/docs/uk/hosting/deno-deploy.md
  site/docs/uk/hosting/supabase.md
  site/docs/zh/hosting/deno-deploy.md
  site/docs/zh/hosting/supabase.md
Labels: not translatable

#921 Improve homepage stickers
  site/docs/.vitepress/theme/layout/HomeHeroInfo.vue
  site/docs/README.md
  site/docs/es/README.md
  site/docs/id/README.md
  site/docs/public/icons/beach-animation.tgs
  site/docs/public/icons/beach-animation.webp
  site/docs/public/icons/beach.svg
  site/docs/public/icons/palette-animation.tgs
  site/docs/public/icons/palette-animation.webp
  site/docs/public/icons/palette.svg
  site/docs/public/icons/rocket-animation.tgs
  site/docs/public/icons/rocket-animation.webp
  site/docs/public/icons/rocket.svg
  site/docs/uk/README.md
  site/docs/zh/README.md
  site/package-lock.json
  site/package.json
Labels: not translatable, chore

#926 [Portuguese] translate commands.md
  site/docs/pt/guide/commands.md
Labels: not translatable

#928 [Portuguese] translate errors.md
  site/docs/pt/guide/errors.md
Labels: not translatable

#931 [Portuguese] translate deployment-types.md
  site/docs/pt/guide/deployment-types.md
Labels: not translatable
