Repository grammyjs/website, pull requests merged in 2023-03, with the labels that each got.

#636 Remove notifier
  .github/workflows/deploy.yml
  README.md
  notifier/.vscode/settings.json
  notifier/README.md
  notifier/db.ts
  notifier/deno.json
  notifier/deno.lock
  notifier/env.ts
  notifier/import_map.json
  notifier/labels.json
  notifier/main.ts
  notifier/utils.ts
Labels: not translatable

#637 Rephrase words in Indonesian translations
  site/docs/id/guide/deployment-types.md
Labels: typo, not translatable, :indonesia: ID

#639 Update filter query count
  site/docs/es/guide/filter-queries.md
  site/docs/guide/filter-queries.md
  site/docs/id/guide/filter-queries.md
Labels: not translatable

#640 (Ukrainian) Translate main guide page
  site/docs/uk/guide/README.md
Labels: 🇺🇦 UK

#585 Document the chat members plugin
  site/docs/.vuepress/configs/en.ts
  site/docs/.vuepress/configs/id.ts
  site/docs/id/plugins/chat-members.md
  site/docs/id/plugins/parse-mode.md
  site/docs/plugins/chat-members.md
Labels: ready for translation, :indonesia: ID

#641 Add a newline and link to Hosting section
  site/docs/guide/introduction.md
  site/docs/id/guide/introduction.md
Labels: ready for translation, :es: ES, :indonesia: ID, 🇺🇦 UK

#646 [Spanish] #641
  site/docs/es/guide/introduction.md
Labels: not translatable, :es: ES

#644 [Ukrainian] Translate `/resources/about.md`
  site/docs/uk/resources/about.md
Labels: not translatable, 🇺🇦 UK

#643 [Ukrainian] Translate `/plugins/README.md`
  site/docs/uk/plugins/README.md
Labels: not translatable, 🇺🇦 UK

#642 Finalize #585
  site/docs/es/plugins/chat-members.md
  site/docs/id/plugins/chat-members.md
  site/docs/plugins/chat-members.md
Labels: ready for translation, :es: ES, :indonesia: ID

#587 Add Cloudflare Workers hosting guide
  site/docs/.vuepress/configs/en.ts
  site/docs/.vuepress/configs/es.ts
  site/docs/.vuepress/configs/id.ts
  site/docs/es/hosting/cloudflare-workers.md
  site/docs/hosting/cloudflare-workers.md
  site/docs/id/hosting/cloudflare-workers.md
Labels: ready for translation, :es: ES, :indonesia: ID

#649 Globes for language switching
  site/docs/.vuepress/configs/en.ts
  site/docs/.vuepress/configs/es.ts
  site/docs/.vuepress/configs/id.ts
Labels: not translatable

#650 [Ukrainian] Improve navigation
  site/docs/.vuepress/configs/uk.ts
Labels: not translatable, 🇺🇦 UK

#648 [Ukrainian] Translate `/guide/context.md`
  site/docs/uk/guide/context.md
Labels: not translatable, 🇺🇦 UK

#660 Revert "feat: use Deno for sitemap generation"
  site/package.json
Labels: not translatable, chore

#656 [Ukrainian] Improve `/README.md`
  site/docs/uk/README.md
Labels: not translatable, 🇺🇦 UK

#657 [Ukrainian] Improve navbar
  site/docs/.vuepress/configs/uk.ts
Labels: not translatable, 🇺🇦 UK

#653 [Ukrainian] Translate `/guide/api.md`
  site/docs/uk/guide/api.md
Labels: not translatable, 🇺🇦 UK

#655 [Chinese] Fixes and improvements
  .vscode/settings.json
  site/docs/zh/advanced/structuring.md
  site/docs/zh/guide/deployment-types.md
  site/docs/zh/guide/introduction.md
  site/docs/zh/hosting/fly.md
  site/docs/zh/plugins/README.md
  site/docs/zh/plugins/conversations.md
  site/docs/zh/plugins/files.md
  site/docs/zh/plugins/fluent.md
  site/docs/zh/plugins/runner.md
Labels: not translatable, :cn: ZH

#662 Migrate back to the Deno-powered sitemap generation
  site/package-lock.json
  site/package.json
Labels: not translatable

#668 Pass Translation Guard when there’s a “time-sensitive” label
  .github/workflows/translation-guard.yml
Labels: not translatable

#666 Update Bot API version to 6.6
  site/docs/README.md
  site/docs/es/README.md
Labels: :es: ES, to merge on release, time-sensitive

#669 Translate Bot API 6.6 Update
  site/docs/es/README.md
  site/docs/id/README.md
  site/docs/zh/README.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID

#652 Inspect sent messages
  site/docs/es/guide/basics.md
  site/docs/guide/basics.md
  site/docs/id/guide/basics.md
  site/docs/zh/guide/basics.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID

#658 [Ukrainian] Translate `/guide/filter-queries.md`
  site/docs/uk/guide/filter-queries.md
Labels: not translatable, 🇺🇦 UK

#659 [Ukrainian] Translate `/guide/commands.md`
  site/docs/uk/guide/commands.md
Labels: not translatable, 🇺🇦 UK

#671 Bot tokens everywhere
  site/docs/es/guide/getting-started.md
  site/docs/guide/getting-started.md
  site/docs/id/guide/getting-started.md
  site/docs/zh/guide/getting-started.md
  site/docs/zh/hosting/heroku.md
  site/docs/zh/plugins/files.md
  site/docs/zh/plugins/i18n.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID

#678 Improve Translation Guard
  .github/workflows/translation-guard.yml
Labels: not translatable, chore

#684 Fix typo
  .github/workflows/translation-guard.yml
Labels: not translatable

#686 Log errors
  .github/workflows/translation-guard.yml
Labels: not translatable

#687 Name step
  .github/workflows/translation-guard.yml
Labels: not translatable

#688 Repair Translation Guard
  .github/workflows/translation-guard.yml
Labels: not translatable, chore

#677 Fix #676
  site/docs/es/plugins/session.md
  site/docs/id/plugins/session.md
  site/docs/plugins/session.md
  site/docs/zh/plugins/session.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID

#685 [Indonesian] Add explanation about this 34-second video
  site/docs/id/guide/introduction.md
Labels: not translatable, :indonesia: ID

#689 Leave a thank you note
  site/docs/.vuepress/client.ts
  site/docs/.vuepress/components/ThankYou.vue
  site/docs/README.md
  site/docs/es/README.md
  site/docs/id/README.md
  site/docs/zh/README.md
  site/package-lock.json
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID

#700 Fix typo in `bot.command()` parameter
  site/docs/es/plugins/transformer-throttler.md
  site/docs/id/plugins/transformer-throttler.md
  site/docs/plugins/transformer-throttler.md
  site/docs/zh/plugins/transformer-throttler.md
Labels: typo, ready for translation, :es: ES, :cn: ZH, :indonesia: ID

#705 Improve consistency
  site/docs/es/advanced/middleware.md
  site/docs/es/advanced/reliability.md
  site/docs/es/advanced/scaling.md
  site/docs/es/advanced/structuring.md
  site/docs/es/guide/context.md
  site/docs/es/guide/middleware.md
  site/docs/es/hosting/fly.md
  site/docs/es/hosting/heroku.md
  site/docs/es/hosting/supabase.md
  site/docs/es/hosting/vercel.md
  site/docs/es/plugins/chat-members.md
  site/docs/es/plugins/files.md
  site/docs/es/plugins/menu.md
  site/docs/es/plugins/runner.md
  site/docs/hosting/fly.md
  site/docs/hosting/heroku.md
  site/docs/id/README.md
  site/docs/id/advanced/middleware.md
  site/docs/id/advanced/reliability.md
  site/docs/id/advanced/scaling.md
  site/docs/id/advanced/structuring.md
  site/docs/id/advanced/transformers.md
  site/docs/id/guide/context.md
  site/docs/id/guide/getting-started.md
  site/docs/id/guide/introduction.md
  site/docs/id/guide/middleware.md
  site/docs/id/hosting/cloudflare-workers.md
  site/docs/id/hosting/fly.md
  site/docs/id/hosting/heroku.md
  site/docs/id/hosting/supabase.md
  site/docs/id/hosting/vercel.md
  site/docs/id/plugins/chat-members.md
  site/docs/id/plugins/conversations.md
  site/docs/id/plugins/files.md
  site/docs/id/plugins/fluent.md
  site/docs/id/plugins/i18n.md
  site/docs/id/plugins/menu.md
  site/docs/id/plugins/runner.md
  site/docs/id/resources/comparison.md
  site/docs/zh/advanced/middleware.md
  site/docs/zh/advanced/reliability.md
  site/docs/zh/advanced/scaling.md
  site/docs/zh/advanced/structuring.md
  site/docs/zh/guide/context.md
  site/docs/zh/guide/middleware.md
  site/docs/zh/hosting/fly.md
  site/docs/zh/hosting/heroku.md
  site/docs/zh/hosting/supabase.md
  site/docs/zh/hosting/vercel.md
  site/docs/zh/plugins/chat-members.md
  site/docs/zh/plugins/files.md
  site/docs/zh/plugins/i18n.md
  site/docs/zh/plugins/menu.md
  site/docs/zh/plugins/runner.md
  site/docs/zh/plugins/session.md
Labels: typo, not translatable, :es: ES, :cn: ZH, style, :indonesia: ID

#623 Document runner 2.0 feats
  site/docs/es/plugins/runner.md
  site/docs/id/plugins/runner.md
  site/docs/plugins/runner.md
  site/docs/zh/plugins/runner.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID

#712 [Spanish] Fix typos
  site/docs/es/plugins/runner.md
Labels: typo, not translatable, :es: ES

#713 Fix issues in code examples
  site/docs/advanced/proxy.md
  site/docs/es/advanced/proxy.md
  site/docs/id/advanced/proxy.md
  site/docs/zh/advanced/proxy.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID

#681 [Ukrainian] Translate `/plugins/middlewares.md`
  site/docs/uk/plugins/middlewares.md
Labels: not translatable, 🇺🇦 UK

#680 [Ukrainian] Translate `/plugins/console-time.md`
  site/docs/uk/plugins/console-time.md
Labels: not translatable, 🇺🇦 UK

#682 [Ukrainian] Translate `/plugins/autoquote.md`
  site/docs/uk/plugins/autoquote.md
Labels: not translatable, 🇺🇦 UK

#679 [Ukrainian] Translate `/plugins/guide.md`
  site/docs/uk/plugins/guide.md
Labels: not translatable, 🇺🇦 UK

#672 [Ukrainian] Translate `/guide/inline-queries.md`
  site/docs/uk/guide/inline-queries.md
Labels: not translatable, 🇺🇦 UK

#675 [Ukrainian] Translate `/guide/games.md`
  site/docs/uk/guide/games.md
Labels: not translatable, 🇺🇦 UK

#667 [Ukrainian] Translate `/guide/middleware.md`
  site/docs/uk/guide/middleware.md
Labels: not translatable, 🇺🇦 UK

#631 Add Firebase Functions hosting guide
  site/docs/hosting/firebase.md
Labels: ready for translation

#654 [Ukrainian] Translate `/resources/comparison.md`
  site/docs/uk/resources/comparison.md
Labels: not translatable, 🇺🇦 UK

#722 Define `Bot`
  site/docs/es/plugins/i18n.md
  site/docs/id/plugins/i18n.md
  site/docs/plugins/i18n.md
  site/docs/zh/plugins/i18n.md
Labels: not translatable, :es: ES, :cn: ZH, :indonesia: ID

#718 Add a note regarding multithreading
  site/docs/es/plugins/runner.md
  site/docs/id/plugins/runner.md
  site/docs/plugins/runner.md
  site/docs/zh/plugins/runner.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID

#734 Fix broken anchor link
  site/docs/es/plugins/runner.md
Labels: not translatable, :es: ES

#737 [Chinese] Improve consistency
  site/docs/zh/plugins/i18n.md
Labels: not translatable, :cn: ZH

#716 Add Firebase Functions hosting guide (#631)
  site/docs/.vuepress/configs/en.ts
  site/docs/.vuepress/configs/es.ts
  site/docs/.vuepress/configs/id.ts
  site/docs/.vuepress/configs/zh.ts
  site/docs/es/hosting/firebase.md
  site/docs/hosting/firebase.md
  site/docs/id/hosting/firebase.md
  site/docs/zh/hosting/firebase.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID

#730 [Ukrainian] Translate `/hosting/supabase.md`
  site/docs/uk/hosting/supabase.md
Labels: not translatable, 🇺🇦 UK

#729 [Ukrainian] Translate `/hosting/heroku.md`
  site/docs/uk/hosting/heroku.md
Labels: not translatable, 🇺🇦 UK

#727 [Ukrainian] Translate `/hosting/fly.md`
  site/docs/uk/hosting/fly.md
Labels: not translatable, 🇺🇦 UK

#726 [Ukrainian] Translate `/hosting/deno-deploy.md`
  site/docs/uk/hosting/deno-deploy.md
Labels: not translatable, 🇺🇦 UK

#740 Use /types everywhere
  site/docs/es/guide/context.md
  site/docs/guide/context.md
  site/docs/id/guide/context.md
  site/docs/zh/guide/context.md
Labels: not translatable, :es: ES, :cn: ZH, :indonesia: ID

#728 [Ukrainian] Translate `/hosting/gcf.md`
  site/docs/uk/hosting/gcf.md
Labels: not translatable, 🇺🇦 UK

#742 Fix determining the correct language
  site/docs/.vuepress/components/LanguagePopup.vue
Labels: not translatable, chore

#732 [Ukrainian] Translate `/hosting/vps.md`
  site/docs/uk/hosting/vps.md
Labels: not translatable, 🇺🇦 UK

#731 [Ukrainian] Translate `/hosting/vercel.md`
  site/docs/uk/hosting/vercel.md
Labels: not translatable, 🇺🇦 UK

#725 [Ukrainian] Translate `/hosting/cloudflare-workers.md`
  site/docs/uk/hosting/cloudflare-workers.md
Labels: not translatable, 🇺🇦 UK

#724 [Ukrainian] Translate `/hosting/comparison.md`
  site/docs/uk/guide/basics.md
  site/docs/uk/guide/context.md
  site/docs/uk/guide/introduction.md
  site/docs/uk/guide/middleware.md
  site/docs/uk/hosting/comparison.md
  site/docs/uk/plugins/README.md
  site/docs/uk/plugins/guide.md
  site/docs/uk/plugins/middlewares.md
  site/docs/uk/resources/about.md
  site/docs/uk/resources/comparison.md
Labels: not translatable, 🇺🇦 UK

#735 [Ukrainian] Translate `/resources/faq.md`
  site/docs/uk/resources/faq.md
Labels: not translatable, 🇺🇦 UK

#690 [Ukrainian] Translate `/advanced/README.md`
  site/docs/uk/advanced/README.md
Labels: not translatable, 🇺🇦 UK

#741 Implement language popup
  site/docs/.vuepress/client.ts
  site/docs/.vuepress/components/LanguagePopup.vue
  site/docs/.vuepress/styles/_vars-dark.scss
  site/docs/.vuepress/styles/_vars.scss
  site/docs/README.md
Labels: not translatable

#748 Fix https://t.me/grammyjs/122939
  site/docs/.vuepress/components/LanguagePopup.vue
Labels: not translatable, chore

#753 [Ukrainian] Translate `/plugins/stateless-question.md`
  site/docs/uk/plugins/stateless-question.md
Labels: not translatable, 🇺🇦 UK

#751 [Ukrainian] Translate `/plugins/auto-retry.md`
  site/docs/uk/plugins/auto-retry.md
Labels: not translatable, 🇺🇦 UK

#750 [Ukrainian] Translate `/plugins/transformer-throttler.md`
  site/docs/uk/plugins/transformer-throttler.md
Labels: not translatable, 🇺🇦 UK

#697 [Ukrainian] Translate `/advanced/proxy.md`
  site/docs/uk/advanced/proxy.md
Labels: not translatable, 🇺🇦 UK

#695 [Ukrainian] Translate `/advanced/flood.md`
  site/docs/uk/advanced/flood.md
Labels: not translatable, 🇺🇦 UK

#674 [Ukrainian] Translate `/guide/files.md`
  site/docs/uk/guide/files.md
Labels: not translatable, 🇺🇦 UK

#691 [Ukrainian] Translate `/advanced/middleware.md`
  site/docs/uk/advanced/middleware.md
Labels: not translatable, 🇺🇦 UK

#692 [Ukrainian] Translate `/advanced/structuring.md`
  site/docs/uk/advanced/structuring.md
Labels: not translatable, 🇺🇦 UK

#752 [Ukrainian] Translate `/plugins/hydrate.md`
  site/docs/uk/plugins/hydrate.md
Labels: not translatable, 🇺🇦 UK

#756 Fix typo
  site/docs/plugins/emoji.md
Labels: typo, not translatable

#694 [Ukrainian] Translate `/advanced/reliability.md`
  site/docs/uk/advanced/reliability.md
Labels: not translatable, 🇺🇦 UK

#696 [Ukrainian] Translate `/advanced/transformers.md`
  site/docs/uk/advanced/transformers.md
Labels: not translatable, 🇺🇦 UK

#698 [Ukrainian] Translate `/advanced/deployment.md`
  site/docs/uk/advanced/deployment.md
Labels: not translatable, 🇺🇦 UK

#743 [Ukrainian] Translate `/plugins/emoji.md`
  site/docs/uk/plugins/emoji.md
Labels: not translatable, 🇺🇦 UK

#745 [Ukrainian] Translate `/plugins/chat-members.md`
  site/docs/uk/plugins/chat-members.md
Labels: not translatable, 🇺🇦 UK

#749 [Ukrainian] Translate `/plugins/ratelimiter.md`
  site/docs/uk/plugins/ratelimiter.md
Labels: not translatable, 🇺🇦 UK

#758 Update README.md and ThankYou.vue
  site/docs/.vuepress/components/ThankYou.vue
  site/docs/README.md
Labels: time-sensitive

#759 Fix punctuation
  site/docs/README.md
Labels: time-sensitive

#746 [Ukrainian] Translate `/plugins/files.md`
  site/docs/uk/plugins/files.md
Labels: not translatable, 🇺🇦 UK

#739 Sync framework adapters and drop the runtime column
  site/docs/es/guide/deployment-types.md
  site/docs/guide/deployment-types.md
  site/docs/id/guide/deployment-types.md
  site/docs/zh/guide/deployment-types.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID

#761 Fix line highlight
  site/docs/es/plugins/conversations.md
  site/docs/id/plugins/conversations.md
  site/docs/plugins/conversations.md
  site/docs/zh/plugins/conversations.md
Labels: not translatable, :es: ES, :cn: ZH, :indonesia: ID

#760 Translate #758 and #759
  site/docs/README.md
  site/docs/es/README.md
  site/docs/id/README.md
  site/docs/zh/README.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID

#670 [Ukrainian] Translate `/guide/errors.md`
  site/docs/uk/guide/errors.md
Labels: not translatable, 🇺🇦 UK

#693 [Ukrainian] Translate `/advanced/scaling.md`
  site/docs/uk/advanced/scaling.md
Labels: not translatable, 🇺🇦 UK

#757 [Ukrainian] Translate `/hosting/firebase.md`
  site/docs/uk/hosting/firebase.md
Labels: not translatable, 🇺🇦 UK
