Repository grammyjs/website, pull requests merged in 2023-01, with the labels that each got.

#576 feat: recommend parse-mode in FAQ
  site/docs/es/resources/faq.md
  site/docs/id/resources/faq.md
  site/docs/resources/faq.md
Labels: ready for translation, :es: ES, :indonesia: ID

#580 style: move determiners out of link texts
  TRANSLATING.md
  site/docs/advanced/deployment.md
  site/docs/advanced/reliability.md
  site/docs/advanced/scaling.md
  site/docs/guide/context.md
  site/docs/guide/introduction.md
  site/docs/hosting/heroku.md
  site/docs/plugins/i18n.md
  site/docs/plugins/menu.md
  site/docs/plugins/router.md
  site/docs/plugins/runner.md
  site/docs/plugins/session.md
  site/docs/plugins/transformer-throttler.md
  site/docs/resources/faq.md
Labels: not translatable, style

#581 style: revert an unwanted change and make a minor improvement
  site/docs/advanced/deployment.md
  site/docs/guide/introduction.md
Labels: not translatable

#579 feat: refer to bot link syntax
  site/docs/es/guide/commands.md
  site/docs/guide/commands.md
  site/docs/id/guide/commands.md
Labels: ready for translation, :es: ES, :indonesia: ID

#582 Translate #578 to Spanish
  site/docs/es/plugins/conversations.md
Labels: not translatable, :es: ES

#583 Refactor and update dependencies
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  .github/workflows/format.yml
  .gitignore
  .vscode/extensions.json
  site/.gitignore
  site/.npmrc
  site/docs/.vuepress/styles/_code.scss
  site/docs/.vuepress/styles/_custom-container.scss
  site/docs/.vuepress/styles/_vars-dark.scss
  site/docs/.vuepress/styles/_vars.scss
  site/docs/.vuepress/styles/index.scss
  site/package-lock.json
  site/package.json
Labels: not translatable, chore

#586 Update copyright years
  LICENSE
  site/docs/README.md
  site/docs/es/README.md
  site/docs/id/README.md
Labels: not translatable
