Repository grammyjs/website, pull requests merged in 2023-11, with the labels that each got.

#937 [Portuguese] translate advanced/README.md
  site/docs/pt/advanced/README.md
Labels: not translatable

#940 [Portuguese] translate advanced/deployment.md
  logos/Y-fit 2.svg
  site/.markdownlint 2.jsonc
  site/docs/pt/advanced/deployment.md
  site/docs/public/images/Y 2.svg
  site/docs/public/images/grammY 2.svg
Labels: not translatable, :brazil: PT

#933 [Portuguese] translate files.md
  site/docs/pt/guide/files.md
Labels: not translatable, :brazil: PT

#935 [Portuguese] translate games.md
  site/docs/pt/guide/games.md
Labels: not translatable, :brazil: PT

#938 [Portuguese] translate advanced/middleware.md
  site/docs/pt/advanced/middleware.md
Labels: not translatable, :brazil: PT

#939 [Portuguese] translate advanced/structuring.md
  site/docs/pt/advanced/structuring.md
Labels: not translatable, :brazil: PT

#943 [Portuguese] translate plugins/README.md
  site/docs/pt/plugins/README.md
Labels: not translatable

#946 Update link checker
  deno.jsonc
Labels: not translatable

#947 Add Algolia crawler config
  algolia-crawler-config.ts
Labels: not translatable

#948 Do not display private props and methods
  site/api/components/Class.tsx
  site/api/components/Class/Constructors.tsx
  site/api/components/Properties.tsx
Labels: not translatable

#949 Link to the start of the guide, not the second section
  site/docs/README.md
  site/docs/es/README.md
  site/docs/id/README.md
  site/docs/uk/README.md
  site/docs/zh/README.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#952 [Ukrainian] Create demo pages
  site/docs/uk/demo/README.md
  site/docs/uk/demo/examples.md
Labels: not translatable, :ukraine: UK

#954 Cancel pending builds when a commit is pushed
  .github/workflows/build.yml
Labels: not translatable

#951 [Ukrainian] Translate alts
  site/docs/uk/README.md
Labels: not translatable, :ukraine: UK

#953 [Ukrainian] Translate untranslated strings
  site/docs/.vitepress/configs/locales/uk.ts
Labels: not translatable, :ukraine: UK
