Repository grammyjs/website, pull requests merged in 2024-01, with the labels that each got.

#976 Add Commit Messages section to the Contribution Guide
  CONTRIBUTING.md
Labels: not translatable

#977 Fix typos
  site/docs/guide/basics.md
  site/docs/guide/context.md
  site/docs/guide/reactions.md
  site/docs/plugins/autoquote.md
  site/docs/plugins/emoji.md
Labels: typo, not translatable

#961 Fix links
  site/docs/advanced/deployment.md
  site/docs/es/advanced/deployment.md
  site/docs/es/advanced/structuring.md
  site/docs/es/guide/filter-queries.md
  site/docs/es/hosting/supabase.md
  site/docs/es/hosting/vercel.md
  site/docs/es/hosting/vps.md
  site/docs/es/plugins/console-time.md
  site/docs/guide/filter-queries.md
  site/docs/hosting/supabase.md
  site/docs/hosting/vercel.md
  site/docs/hosting/vps.md
  site/docs/id/advanced/deployment.md
  site/docs/id/guide/filter-queries.md
  site/docs/id/hosting/supabase.md
  site/docs/id/hosting/vercel.md
  site/docs/id/hosting/vps.md
  site/docs/id/plugins/console-time.md
  site/docs/plugins/console-time.md
  site/docs/uk/advanced/deployment.md
  site/docs/uk/guide/filter-queries.md
  site/docs/uk/guide/introduction.md
  site/docs/uk/hosting/supabase.md
  site/docs/uk/hosting/vercel.md
  site/docs/uk/hosting/vps.md
  site/docs/uk/plugins/console-time.md
  site/docs/zh/advanced/deployment.md
  site/docs/zh/guide/filter-queries.md
  site/docs/zh/guide/introduction.md
  site/docs/zh/hosting/supabase.md
  site/docs/zh/hosting/vercel.md
  site/docs/zh/hosting/vps.md
  site/docs/zh/plugins/console-time.md
Labels: typo, not translatable

#978 Fix typos
  site/docs/guide/reactions.md
Labels: typo, not translatable

#979 Fix contributor names not displaying
  site/docs/.vitepress/components/ThankYou.vue
Labels: not translatable, chore

#981 Fix import specifiers
  site/docs/es/plugins/session.md
Labels: not translatable, :es: ES

#982 Fix link
  site/docs/es/hosting/deno-deploy.md
  site/docs/hosting/deno-deploy.md
  site/docs/id/hosting/deno-deploy.md
  site/docs/uk/hosting/deno-deploy.md
  site/docs/zh/hosting/deno-deploy.md
Labels: not translatable

#980 Improve headings
  site/docs/es/plugins/autoquote.md
  site/docs/id/plugins/autoquote.md
  site/docs/plugins/autoquote.md
  site/docs/uk/plugins/autoquote.md
  site/docs/zh/plugins/autoquote.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#973 List missing webhook adapters
  site/docs/es/guide/deployment-types.md
  site/docs/guide/deployment-types.md
  site/docs/id/guide/deployment-types.md
  site/docs/uk/guide/deployment-types.md
  site/docs/zh/guide/deployment-types.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#985 Add missing brackets
  site/docs/es/plugins/runner.md
  site/docs/id/plugins/runner.md
  site/docs/plugins/runner.md
  site/docs/uk/plugins/runner.md
  site/docs/zh/plugins/runner.md
Labels: not translatable

#972 Translate #971
  site/docs/.vitepress/configs/locales/es.ts
  site/docs/.vitepress/configs/locales/id.ts
  site/docs/.vitepress/configs/locales/uk.ts
  site/docs/.vitepress/configs/locales/zh.ts
  site/docs/es/README.md
  site/docs/es/guide/basics.md
  site/docs/es/guide/context.md
  site/docs/es/guide/filter-queries.md
  site/docs/es/guide/reactions.md
  site/docs/es/plugins/autoquote.md
  site/docs/es/plugins/emoji.md
  site/docs/id/README.md
  site/docs/id/guide/basics.md
  site/docs/id/guide/context.md
  site/docs/id/guide/filter-queries.md
  site/docs/id/guide/reactions.md
  site/docs/id/plugins/autoquote.md
  site/docs/id/plugins/emoji.md
  site/docs/uk/README.md
  site/docs/uk/guide/basics.md
  site/docs/uk/guide/context.md
  site/docs/uk/guide/filter-queries.md
  site/docs/uk/guide/reactions.md
  site/docs/uk/plugins/autoquote.md
  site/docs/uk/plugins/emoji.md
  site/docs/zh/README.md
  site/docs/zh/guide/basics.md
  site/docs/zh/guide/context.md
  site/docs/zh/guide/filter-queries.md
  site/docs/zh/guide/reactions.md
  site/docs/zh/plugins/autoquote.md
  site/docs/zh/plugins/emoji.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#987 [Chinese] Fix typos
  site/docs/zh/resources/comparison.md
Labels: typo, not translatable, :cn: ZH
