Repository grammyjs/website, pull requests merged in 2024-04, with the labels that each got.

#1035 Cache deps
  site/api/.gitignore
  site/api/api_gen.tsx
  site/api/deno.jsonc
Labels: not translatable, chore

#1030 Update dependencies
  site/docs/.vitepress/components/NavBar.vue
  site/docs/.vitepress/components/NavBarExtra.vue
  site/docs/.vitepress/components/NavScreen.vue
  site/docs/.vitepress/components/NotFound.vue
  site/docs/.vitepress/config.ts
  site/docs/.vitepress/deps/hash.ts
  site/docs/.vitepress/deps/langs.ts
  site/docs/.vitepress/deps/shared.ts
  site/docs/.vitepress/deps/utils.ts
  site/package-lock.json
  site/package.json
Labels: not translatable, chore

#1031 Add troubleshooting notes
  README.md
Labels: not translatable

#1037 Add missing comma
  site/docs/guide/files.md
Labels: typo, not translatable

#1019 Explain how types can be used for storage enhancements
  site/docs/es/plugins/session.md
  site/docs/id/plugins/session.md
  site/docs/plugins/session.md
  site/docs/uk/plugins/session.md
  site/docs/zh/plugins/session.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#781 Improve VPS hosting guide, add Hostinger to the hosting comparison
  site/docs/es/hosting/comparison.md
  site/docs/es/hosting/vps.md
  site/docs/hosting/comparison.md
  site/docs/hosting/vps.md
  site/docs/id/hosting/comparison.md
  site/docs/id/hosting/vps.md
  site/docs/uk/hosting/comparison.md
  site/docs/uk/hosting/vps.md
  site/docs/zh/hosting/comparison.md
  site/docs/zh/hosting/vps.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#923 Add tip for Vercel Edge Functions
  site/docs/es/hosting/vercel.md
  site/docs/hosting/vercel.md
  site/docs/id/hosting/vercel.md
  site/docs/uk/hosting/vercel.md
  site/docs/zh/hosting/vercel.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#1033 Minor fixes after the 7.2 compat release
  site/docs/es/guide/context.md
  site/docs/es/guide/filter-queries.md
  site/docs/guide/context.md
  site/docs/guide/filter-queries.md
  site/docs/id/guide/context.md
  site/docs/id/guide/filter-queries.md
  site/docs/uk/guide/context.md
  site/docs/uk/guide/filter-queries.md
  site/docs/zh/guide/context.md
  site/docs/zh/guide/filter-queries.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#1017 Explain plugin refs in overview
  site/docs/es/guide/README.md
  site/docs/guide/README.md
  site/docs/id/guide/README.md
  site/docs/uk/guide/README.md
  site/docs/zh/guide/README.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#1038 Fix build error
  site/.npmrc
  site/docs/.vitepress/components/NavBar.vue
Labels: not translatable, chore

#1021 Give more structure to the files guide
  site/docs/es/guide/files.md
  site/docs/guide/files.md
  site/docs/id/guide/files.md
  site/docs/uk/guide/files.md
  site/docs/zh/guide/files.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#1008 Update docs about API ref
  site/docs/es/guide/README.md
  site/docs/guide/README.md
  site/docs/id/guide/README.md
  site/docs/uk/guide/README.md
  site/docs/zh/guide/README.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#1028 Translate `docFooter`
  site/docs/.vitepress/configs/locales/es.ts
  site/docs/.vitepress/configs/locales/uk.ts
  site/docs/.vitepress/configs/locales/zh.ts
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#1039 Sync #1032 with Spanish
  site/docs/es/README.md
Labels: not translatable, :es: ES

#1040 Local Bot API servers and DC locations
  site/docs/es/guide/api.md
  site/docs/es/guide/files.md
  site/docs/guide/api.md
  site/docs/guide/files.md
  site/docs/id/guide/api.md
  site/docs/id/guide/files.md
  site/docs/uk/guide/api.md
  site/docs/uk/guide/files.md
  site/docs/zh/guide/api.md
  site/docs/zh/guide/files.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#1006 Update auto-retry docs for version 2.0 of the plugin
  site/docs/es/advanced/flood.md
  site/docs/es/plugins/auto-retry.md
  site/docs/id/plugins/auto-retry.md
  site/docs/plugins/auto-retry.md
  site/docs/uk/plugins/auto-retry.md
  site/docs/zh/plugins/auto-retry.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, merge on release, :ukraine: UK

#1044 Add auto-retry to modules.json
  site/docs/.vitepress/plugins/current-versions/modules.json
Labels: not translatable, chore

#1046 Fix link
  site/docs/es/guide/middleware.md
  site/docs/guide/middleware.md
  site/docs/id/guide/middleware.md
  site/docs/uk/guide/middleware.md
  site/docs/zh/guide/middleware.md
Labels: not translatable

#1034 Document business connections
  deno.jsonc
  site/docs/.vitepress/configs/locales/en.ts
  site/docs/.vitepress/configs/locales/es.ts
  site/docs/.vitepress/configs/locales/id.ts
  site/docs/.vitepress/configs/locales/uk.ts
  site/docs/.vitepress/configs/locales/zh.ts
  site/docs/advanced/business.md
  site/docs/es/advanced/business.md
  site/docs/id/advanced/business.md
  site/docs/uk/advanced/business.md
  site/docs/zh/advanced/business.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#1041 Add links to API guide from Hosting: VPS
  site/docs/es/hosting/vps.md
  site/docs/hosting/vps.md
  site/docs/id/hosting/vps.md
  site/docs/uk/hosting/vps.md
  site/docs/zh/hosting/vps.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#1047 Add missing bracket
  site/docs/es/plugins/router.md
  site/docs/id/plugins/router.md
  site/docs/plugins/router.md
  site/docs/uk/plugins/router.md
  site/docs/zh/plugins/router.md
Labels: typo, not translatable
