Repository grammyjs/website, pull requests merged in 2024-06, with the labels that each got.

#1061 Add mvps.net to the hosting comparison (#1056)
  site/docs/es/hosting/comparison.md
  site/docs/hosting/comparison.md
  site/docs/id/hosting/comparison.md
  site/docs/uk/hosting/comparison.md
  site/docs/zh/hosting/comparison.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#1066 Translate #1065
  site/docs/es/README.md
  site/docs/id/README.md
  site/docs/uk/README.md
  site/docs/zh/README.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#1054 Fix my_chat_member update comment
  site/docs/es/guide/filter-queries.md
  site/docs/guide/filter-queries.md
  site/docs/id/guide/filter-queries.md
  site/docs/uk/guide/filter-queries.md
  site/docs/zh/guide/filter-queries.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#1069 Add note about `allowed_updates` to the menu plugin page
  site/docs/es/plugins/menu.md
  site/docs/id/plugins/menu.md
  site/docs/plugins/menu.md
  site/docs/uk/plugins/menu.md
  site/docs/zh/plugins/menu.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#1058 Update i18n docs with information about Unicode isolation marks (#1053)
  site/docs/es/plugins/i18n.md
  site/docs/id/plugins/i18n.md
  site/docs/plugins/i18n.md
  site/docs/uk/plugins/i18n.md
  site/docs/zh/plugins/i18n.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#1064 Recommend setting WorkingDirectory
  site/docs/es/hosting/vps.md
  site/docs/hosting/vps.md
  site/docs/id/hosting/vps.md
  site/docs/uk/hosting/vps.md
  site/docs/zh/hosting/vps.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#1072 Add `bun` framework adapter
  site/docs/es/guide/deployment-types.md
  site/docs/guide/deployment-types.md
  site/docs/id/guide/deployment-types.md
  site/docs/uk/guide/deployment-types.md
  site/docs/zh/guide/deployment-types.md
Labels: not translatable

#1073 Add missing http:// in apiRoot option
  site/docs/es/guide/api.md
  site/docs/guide/api.md
  site/docs/id/guide/api.md
  site/docs/uk/guide/api.md
  site/docs/zh/guide/api.md
Labels: not translatable

#1071 Add Zeabur to the hosting comparison (#1059)
  site/docs/.vitepress/configs/locales/en.ts
  site/docs/.vitepress/configs/locales/es.ts
  site/docs/.vitepress/configs/locales/id.ts
  site/docs/.vitepress/configs/locales/uk.ts
  site/docs/.vitepress/configs/locales/zh.ts
  site/docs/es/hosting/comparison.md
  site/docs/es/hosting/zeabur-deno.md
  site/docs/es/hosting/zeabur-nodejs.md
  site/docs/hosting/comparison.md
  site/docs/hosting/zeabur-deno.md
  site/docs/hosting/zeabur-nodejs.md
  site/docs/id/hosting/comparison.md
  site/docs/id/hosting/zeabur-deno.md
  site/docs/id/hosting/zeabur-nodejs.md
  site/docs/uk/hosting/comparison.md
  site/docs/uk/hosting/zeabur-deno.md
  site/docs/uk/hosting/zeabur-nodejs.md
  site/docs/zh/hosting/comparison.md
  site/docs/zh/hosting/zeabur-deno.md
  site/docs/zh/hosting/zeabur-nodejs.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#1079 Mention support for Bot API 7.5
  site/docs/README.md
Labels: not translatable, merge on release, time-sensitive

#1052 Fix links and update link tasks
  .github/workflows/check.yml
  deno.jsonc
  site/.gitignore
  site/docs/advanced/flood.md
  site/docs/es/advanced/flood.md
  site/docs/es/guide/reactions.md
  site/docs/es/hosting/comparison.md
  site/docs/es/hosting/fly.md
  site/docs/es/hosting/vercel.md
  site/docs/es/hosting/vps.md
  site/docs/guide/reactions.md
  site/docs/hosting/comparison.md
  site/docs/hosting/fly.md
  site/docs/hosting/vercel.md
  site/docs/hosting/vps.md
  site/docs/id/advanced/flood.md
  site/docs/id/guide/reactions.md
  site/docs/id/hosting/comparison.md
  site/docs/id/hosting/fly.md
  site/docs/id/hosting/vercel.md
  site/docs/id/hosting/vps.md
  site/docs/id/resources/faq.md
  site/docs/resources/faq.md
  site/docs/uk/advanced/flood.md
  site/docs/uk/guide/reactions.md
  site/docs/uk/hosting/comparison.md
  site/docs/uk/hosting/fly.md
  site/docs/uk/hosting/vercel.md
  site/docs/uk/hosting/vps.md
  site/docs/uk/plugins/session.md
  site/docs/zh/advanced/flood.md
  site/docs/zh/guide/reactions.md
  site/docs/zh/hosting/comparison.md
  site/docs/zh/hosting/fly.md
  site/docs/zh/hosting/vercel.md
  site/docs/zh/hosting/vps.md
  site/docs/zh/plugins/auto-retry.md
Labels: not translatable

#1083 Add syntax support for env languages
  site/docs/.vitepress/config.ts
  site/docs/.vitepress/shared/syntaxes/env.tmLanguage.json
  site/docs/es/hosting/cloudflare-workers-nodejs.md
  site/docs/hosting/cloudflare-workers-nodejs.md
  site/docs/id/hosting/cloudflare-workers-nodejs.md
  site/docs/uk/hosting/cloudflare-workers-nodejs.md
  site/docs/zh/hosting/cloudflare-workers-nodejs.md
Labels: not translatable, chore

#1074 Add talk to filter query docs
  site/docs/es/guide/filter-queries.md
  site/docs/guide/filter-queries.md
  site/docs/id/guide/filter-queries.md
  site/docs/uk/guide/filter-queries.md
  site/docs/zh/guide/filter-queries.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#1082 Fix Zeabur Doc
  site/docs/es/hosting/zeabur-deno.md
  site/docs/es/hosting/zeabur-nodejs.md
  site/docs/hosting/zeabur-deno.md
  site/docs/hosting/zeabur-nodejs.md
  site/docs/id/hosting/zeabur-deno.md
  site/docs/id/hosting/zeabur-nodejs.md
  site/docs/uk/hosting/zeabur-deno.md
  site/docs/uk/hosting/zeabur-nodejs.md
  site/docs/zh/hosting/zeabur-deno.md
  site/docs/zh/hosting/zeabur-nodejs.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#1076 Guard against other known limits
  site/docs/advanced/flood.md
  site/docs/es/advanced/flood.md
  site/docs/id/advanced/flood.md
  site/docs/uk/advanced/flood.md
  site/docs/zh/advanced/flood.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#1080 Translate #1079: Mention support for Bot API 7.5
  site/docs/es/README.md
  site/docs/id/README.md
  site/docs/uk/README.md
  site/docs/zh/README.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#1084 Add anchor to ref
  site/docs/es/guide/middleware.md
  site/docs/guide/middleware.md
  site/docs/id/guide/middleware.md
  site/docs/uk/guide/middleware.md
  site/docs/zh/guide/middleware.md
Labels: not translatable

#1075 Rework comparison with other frameworks
  site/docs/es/resources/comparison.md
  site/docs/id/resources/comparison.md
  site/docs/resources/comparison.md
  site/docs/uk/resources/comparison.md
  site/docs/zh/resources/comparison.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK
