Repository grammyjs/website, pull requests merged in 2024-05, with the labels that each got.

#1050 [Spanish] Fix typo
  site/docs/.vitepress/configs/locales/es.ts
Labels: not translatable, :es: ES

#1043 Update Cloudflare Workers guide
  site/docs/es/hosting/cloudflare-workers-nodejs.md
  site/docs/hosting/cloudflare-workers-nodejs.md
  site/docs/id/hosting/cloudflare-workers-nodejs.md
  site/docs/uk/hosting/cloudflare-workers-nodejs.md
  site/docs/zh/hosting/cloudflare-workers-nodejs.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#1048 Update to Bot API 7.3
  site/docs/README.md
  site/docs/es/README.md
  site/docs/es/guide/context.md
  site/docs/guide/context.md
  site/docs/id/README.md
  site/docs/id/guide/context.md
  site/docs/uk/README.md
  site/docs/uk/guide/context.md
  site/docs/zh/README.md
  site/docs/zh/guide/context.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#1056 Add mvps.net
  site/docs/hosting/comparison.md
Labels: ready for translation

#1062 Fix country flag emoji not displayed correctly on chromium based browsers
  site/docs/.vitepress/theme/layout/Layout.vue
  site/docs/.vitepress/theme/style/_fonts.scss
  site/docs/.vitepress/theme/style/_vars.scss
  site/package-lock.json
  site/package.json
Labels: not translatable, chore

#1063 Reorder hosting guides
  site/docs/.vitepress/configs/locales/en.ts
  site/docs/.vitepress/configs/locales/es.ts
  site/docs/.vitepress/configs/locales/id.ts
  site/docs/.vitepress/configs/locales/uk.ts
  site/docs/.vitepress/configs/locales/zh.ts
  site/docs/es/hosting/gcf.md
  site/docs/hosting/gcf.md
  site/docs/id/hosting/gcf.md
  site/docs/uk/hosting/gcf.md
  site/docs/zh/hosting/gcf.md
Labels: not translatable

#1067 Fix syntax highlighting light theme in API ref
  site/api/components/Class/Constructors.tsx
  site/api/components/Class/Method.tsx
  site/api/components/CodeBlock.tsx
  site/api/components/PropertyName.tsx
  site/api/components/styles.tsx
Labels: not translatable, chore

#1070 Fix typo in introduction
  site/docs/guide/introduction.md
Labels: typo, not translatable
