Repository grammyjs/website, pull requests merged in 2024-03, with the labels that each got.

#999 Perf is nice
  site/docs/es/guide/filter-queries.md
  site/docs/guide/filter-queries.md
  site/docs/id/guide/filter-queries.md
  site/docs/uk/guide/filter-queries.md
  site/docs/zh/guide/filter-queries.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#1005 Fix typos
  site/docs/plugins/menu.md
Labels: typo, not translatable

#1007 Remove .prettierrc
  .prettierrc
Labels: not translatable, chore

#1009 Update sitemap-cli to 1.2.0
  site/package.json
Labels: not translatable, chore

#1010 Generate API reference on npm install
  site/package.json
Labels: not translatable, chore

#1013 Use existsSync instead of exists
  site/api/api_gen.tsx
Labels: not translatable, chore

#1014 Skip Markdown linting for API ref
  site/package.json
Labels: not translatable, chore

#1012 Link to new ref from all langs
  site/docs/.vitepress/configs/locales/es.ts
  site/docs/.vitepress/configs/locales/id.ts
  site/docs/.vitepress/configs/locales/uk.ts
  site/docs/.vitepress/configs/locales/zh.ts
Labels: not translatable

#1011 Add option to disable translation button
  .github/workflows/build.yml
  site/.npmrc
  site/api/api_gen.tsx
  site/docs/.vitepress/components/CustomNavBar.vue
  site/docs/.vitepress/components/CustomNavScreen.vue
  site/docs/.vitepress/config.ts
  site/package-lock.json
  site/package.json
Labels: not translatable, chore

#988 Add FAQ about chat history and albums
  site/docs/es/resources/faq.md
  site/docs/id/resources/faq.md
  site/docs/resources/faq.md
  site/docs/uk/resources/faq.md
  site/docs/zh/resources/faq.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#1020 Add links to telegram.tools and the VS Code extension under Resources
  site/docs/.vitepress/configs/locales/en.ts
  site/docs/.vitepress/configs/locales/es.ts
  site/docs/.vitepress/configs/locales/id.ts
  site/docs/.vitepress/configs/locales/uk.ts
  site/docs/.vitepress/configs/locales/zh.ts
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#1026 [UK] Consistently translate "API reference"
  site/docs/uk/plugins/router.md
Labels: not translatable, :ukraine: UK

#1025 Remove useless character
  site/docs/es/plugins/i18n.md
  site/docs/es/plugins/router.md
  site/docs/id/plugins/i18n.md
  site/docs/id/plugins/router.md
  site/docs/plugins/i18n.md
  site/docs/plugins/router.md
  site/docs/uk/plugins/i18n.md
  site/docs/uk/plugins/router.md
  site/docs/zh/plugins/i18n.md
  site/docs/zh/plugins/router.md
Labels: typo, not translatable

#1023 Add ranking system to Algolia search
  site/docs/.vitepress/configs/algolia/crawler.js
Labels: not translatable, chore

#1029 Remove invalid line from crawler config
  site/docs/.vitepress/configs/algolia/crawler.js
Labels: not translatable, chore
