Repository grammyjs/website, pull requests merged in 2024-02, with the labels that each got.

#986 Update autoquote docs
  site/docs/es/plugins/autoquote.md
  site/docs/id/plugins/autoquote.md
  site/docs/plugins/autoquote.md
  site/docs/uk/plugins/autoquote.md
  site/docs/zh/plugins/autoquote.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#984 Fix reaction docs
  site/docs/es/guide/context.md
  site/docs/es/guide/reactions.md
  site/docs/guide/context.md
  site/docs/guide/reactions.md
  site/docs/id/guide/context.md
  site/docs/id/guide/reactions.md
  site/docs/uk/guide/context.md
  site/docs/uk/guide/reactions.md
  site/docs/zh/guide/context.md
  site/docs/zh/guide/reactions.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#989 Update deps
  site/package-lock.json
  site/package.json
Labels: not translatable

#992 Fix build error
  site/docs/.vitepress/deps/hash.ts
  site/docs/.vitepress/deps/langs.ts
  site/docs/.vitepress/deps/shared.ts
  site/docs/.vitepress/deps/utils.ts
  site/tsconfig.json
Labels: not translatable

#994 Bot API 7.1 support
  site/docs/README.md
  site/docs/id/README.md
Labels: time-sensitive

#996 Update deps
  .github/workflows/build.yml
  .github/workflows/check.yml
  site/docs/.vitepress/components/HomeContent.vue
  site/docs/.vitepress/theme/index.ts
  site/docs/.vitepress/theme/style/_normalize.scss
  site/docs/README.md
  site/docs/es/README.md
  site/docs/id/README.md
  site/docs/uk/README.md
  site/docs/zh/README.md
  site/package-lock.json
  site/package.json
Labels: not translatable, chore

#991 Tell users to enable reaction updates
  site/docs/es/guide/reactions.md
  site/docs/guide/reactions.md
  site/docs/id/guide/reactions.md
  site/docs/uk/guide/reactions.md
  site/docs/zh/guide/reactions.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#998 Fix import
  site/docs/es/hosting/heroku.md
  site/docs/hosting/heroku.md
  site/docs/id/hosting/heroku.md
  site/docs/uk/hosting/heroku.md
  site/docs/zh/hosting/heroku.md
Labels: typo, not translatable

#1001 Redirect /ref to API reference
  site/netlify.toml
Labels: not translatable

#1002 Redeploy site when netlify.toml or dependencies change
  .github/workflows/build.yml
Labels: not translatable, chore

#1003 [UK] Fix VPS hosting comparison table
  site/docs/uk/hosting/comparison.md
Labels: not translatable, :ukraine: UK
