Repository grammyjs/website, pull requests merged in 2024-09, with the labels that each got.

#1117 Enable `links:fix` to write files
  deno.jsonc
  site/docs/es/guide/deployment-types.md
  site/docs/es/guide/introduction.md
  site/docs/es/hosting/cloudflare-workers-nodejs.md
  site/docs/es/hosting/fly.md
  site/docs/es/hosting/vps.md
  site/docs/es/plugins/runner.md
  site/docs/guide/introduction.md
  site/docs/hosting/cloudflare-workers-nodejs.md
  site/docs/hosting/fly.md
  site/docs/hosting/vps.md
  site/docs/id/guide/introduction.md
  site/docs/id/hosting/cloudflare-workers-nodejs.md
  site/docs/id/hosting/fly.md
  site/docs/id/hosting/vps.md
  site/docs/id/plugins/runner.md
  site/docs/plugins/runner.md
  site/docs/uk/guide/introduction.md
  site/docs/uk/hosting/cloudflare-workers-nodejs.md
  site/docs/uk/hosting/fly.md
  site/docs/uk/hosting/vps.md
  site/docs/uk/plugins/runner.md
  site/docs/zh/advanced/scaling.md
  site/docs/zh/guide/introduction.md
  site/docs/zh/hosting/cloudflare-workers-nodejs.md
  site/docs/zh/hosting/deno-deploy.md
  site/docs/zh/hosting/fly.md
  site/docs/zh/hosting/heroku.md
  site/docs/zh/hosting/supabase.md
  site/docs/zh/hosting/vps.md
  site/docs/zh/plugins/runner.md
Labels: not translatable, chore

#1116 Mention support for Bot API 7.10
  site/docs/README.md
Labels: not translatable, merge on release, time-sensitive

#1119 Spanish version for Release 7.10
  site/docs/es/README.md
Labels: not translatable, :es: ES

#1118 Translate #1116
  site/docs/es/README.md
  site/docs/id/README.md
  site/docs/uk/README.md
  site/docs/zh/README.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#1122 Require Russian translations
  .github/workflows/translation-guard.yml
Labels: not translatable, 🇷🇺 RU

#1123 Fix Russian 404 pages
  site/netlify.toml
Labels: not translatable, 🇷🇺 RU

#1126 Fix advanced/business.md
  site/docs/ru/advanced/business.md
Labels: 🇷🇺 RU

#1128 Remove Deta from the hosting comparison
  site/docs/es/hosting/comparison.md
  site/docs/hosting/comparison.md
  site/docs/id/hosting/comparison.md
  site/docs/ru/hosting/comparison.md
  site/docs/uk/hosting/comparison.md
  site/docs/zh/hosting/comparison.md
Labels: not translatable

#1125 Russian translation improvements
  site/docs/ru/README.md
  site/docs/ru/advanced/business.md
  site/docs/ru/advanced/flood.md
  site/docs/ru/advanced/middleware.md
  site/docs/ru/advanced/proxy.md
  site/docs/ru/advanced/reliability.md
  site/docs/ru/guide/README.md
  site/docs/ru/guide/api.md
  site/docs/ru/guide/basics.md
  site/docs/ru/guide/context.md
  site/docs/ru/guide/filter-queries.md
  site/docs/ru/guide/introduction.md
  site/docs/ru/guide/reactions.md
  site/docs/ru/plugins/auto-retry.md
  site/docs/ru/plugins/autoquote.md
  site/docs/ru/plugins/chat-members.md
  site/docs/ru/plugins/console-time.md
  site/docs/ru/plugins/emoji.md
  site/docs/ru/resources/about.md
  site/docs/ru/resources/comparison.md
  site/docs/ru/resources/faq.md
Labels: not translatable, 🇷🇺 RU
