Repository grammyjs/website, pull requests merged in 2024-07, with the labels that each got.

#1085 Mention support for Bot API 7.6
  site/docs/README.md
  site/docs/es/README.md
  site/docs/id/README.md
  site/docs/uk/README.md
  site/docs/zh/README.md
Labels: ready for translation, :cn: ZH, merge on release, :ukraine: UK

#1090 Mention support for Bot API 7.7
  site/docs/README.md
Labels: not translatable, merge on release, time-sensitive

#1091 Fix runner ref link
  site/docs/es/plugins/runner.md
  site/docs/id/plugins/runner.md
  site/docs/plugins/runner.md
  site/docs/uk/plugins/runner.md
  site/docs/zh/plugins/runner.md
Labels: typo, not translatable

#1093 Remove Cyclic hosting guide and references to Cyclic
  site/docs/.vitepress/configs/locales/en.ts
  site/docs/.vitepress/configs/locales/es.ts
  site/docs/.vitepress/configs/locales/id.ts
  site/docs/.vitepress/configs/locales/uk.ts
  site/docs/.vitepress/configs/locales/zh.ts
  site/docs/es/hosting/comparison.md
  site/docs/es/hosting/cyclic.md
  site/docs/hosting/comparison.md
  site/docs/hosting/cyclic.md
  site/docs/id/hosting/cyclic.md
  site/docs/uk/hosting/comparison.md
  site/docs/uk/hosting/cyclic.md
  site/docs/zh/hosting/comparison.md
  site/docs/zh/hosting/cyclic.md
Labels: not translatable

#1092 Translate #1090
  site/docs/es/README.md
  site/docs/id/README.md
  site/docs/uk/README.md
  site/docs/zh/README.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#1094 Fix link issues
  .github/workflows/check.yml
  site/docs/es/hosting/cloudflare-workers-nodejs.md
  site/docs/es/hosting/comparison.md
  site/docs/es/hosting/deno-deploy.md
  site/docs/es/hosting/fly.md
  site/docs/es/hosting/vps.md
  site/docs/hosting/cloudflare-workers-nodejs.md
  site/docs/hosting/comparison.md
  site/docs/hosting/deno-deploy.md
  site/docs/hosting/fly.md
  site/docs/hosting/vps.md
  site/docs/id/hosting/cloudflare-workers-nodejs.md
  site/docs/id/hosting/comparison.md
  site/docs/id/hosting/deno-deploy.md
  site/docs/id/hosting/fly.md
  site/docs/id/hosting/vps.md
  site/docs/uk/hosting/cloudflare-workers-nodejs.md
  site/docs/uk/hosting/comparison.md
  site/docs/uk/hosting/deno-deploy.md
  site/docs/uk/hosting/fly.md
  site/docs/uk/hosting/vps.md
  site/docs/uk/resources/comparison.md
  site/docs/zh/hosting/cloudflare-workers-nodejs.md
  site/docs/zh/hosting/comparison.md
  site/docs/zh/hosting/deno-deploy.md
  site/docs/zh/hosting/fly.md
  site/docs/zh/hosting/vps.md
Labels: typo, not translatable, chore

#1098 Fix #1097
  site/docs/es/plugins/inline-query.md
  site/docs/plugins/inline-query.md
Labels: typo, not translatable

#1099 Pass GitHub token to Link Checker
  .github/workflows/check.yml
Labels: not translatable

#1081 Update Deno Deploy guide
  site/docs/es/hosting/deno-deploy.md
  site/docs/hosting/deno-deploy.md
  site/docs/id/hosting/deno-deploy.md
  site/docs/uk/hosting/deno-deploy.md
  site/docs/zh/hosting/deno-deploy.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#1096 Clarify how to stop the bot via grammY runner
  site/docs/es/plugins/runner.md
  site/docs/id/plugins/runner.md
  site/docs/plugins/runner.md
  site/docs/uk/plugins/runner.md
  site/docs/zh/plugins/runner.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#1103 Update translation guide
  TRANSLATING.md
Labels: not translatable

#1095 Document how webhooks are set
  site/docs/es/guide/deployment-types.md
  site/docs/guide/deployment-types.md
  site/docs/id/guide/deployment-types.md
  site/docs/uk/guide/deployment-types.md
  site/docs/zh/guide/deployment-types.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK

#1106 Mention support for Bot API 7.8
  site/docs/README.md
Labels: not translatable, merge on release, time-sensitive
