Repository grammyjs/website, pull requests merged in 2024-12, with the labels that each got.

#1162 Mention support for Bot API 8.1
  site/docs/README.md
Labels: not translatable, merge on release, time-sensitive

#1165 Avoid double install in CI
  .github/workflows/build.yml
Labels: not translatable, chore

#1164 Fix typo in adapter of webhookCallback
  site/docs/es/hosting/vercel.md
  site/docs/hosting/vercel.md
  site/docs/id/hosting/vercel.md
  site/docs/ru/hosting/vercel.md
  site/docs/uk/hosting/vercel.md
  site/docs/zh/hosting/vercel.md
Labels: typo, not translatable

#1170 Add missing word
  site/docs/guide/deployment-types.md
Labels: not translatable

#1171 Fix links after deno2node was moved on GitHub
  site/docs/es/plugins/guide.md
  site/docs/id/plugins/guide.md
  site/docs/plugins/guide.md
  site/docs/ru/plugins/guide.md
  site/docs/uk/plugins/guide.md
  site/docs/zh/plugins/guide.md
Labels: typo, not translatable

#1163 Translate #1162
  site/docs/es/README.md
  site/docs/id/README.md
  site/docs/ru/README.md
  site/docs/uk/README.md
  site/docs/zh/README.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK, :ru: RU

#1169 Translate #1166
  site/docs/es/guide/deployment-types.md
  site/docs/es/hosting/vercel.md
  site/docs/guide/deployment-types.md
  site/docs/hosting/vercel.md
  site/docs/id/guide/deployment-types.md
  site/docs/id/hosting/vercel.md
  site/docs/ru/guide/deployment-types.md
  site/docs/ru/hosting/vercel.md
  site/docs/uk/guide/deployment-types.md
  site/docs/uk/hosting/vercel.md
  site/docs/zh/guide/deployment-types.md
  site/docs/zh/hosting/vercel.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK, :ru: RU

#1168 Fix code example for similar commands
  site/docs/es/plugins/commands.md
  site/docs/id/plugins/commands.md
  site/docs/plugins/commands.md
  site/docs/ru/plugins/commands.md
  site/docs/uk/plugins/commands.md
  site/docs/zh/plugins/commands.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK, :ru: RU

#1173 Fix return type (#1172)
  site/docs/advanced/transformers.md
  site/docs/es/advanced/transformers.md
  site/docs/id/advanced/transformers.md
  site/docs/ru/advanced/transformers.md
  site/docs/uk/advanced/transformers.md
  site/docs/zh/advanced/transformers.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK, :ru: RU

#1161 Fix wrong limit for Cloudflare Workers
  site/docs/hosting/comparison.md
Labels: typo
