Repository grammyjs/website, pull requests merged in 2024-08, with the labels that each got.

#1108 [Chinese] Nitpick
  site/docs/zh/advanced/business.md
Labels: not translatable, :cn: ZH

#1111 Replace --- by — in translation guide
  TRANSLATING.md
Labels: typo, not translatable, style

#1107 Translate #1106
  site/docs/es/README.md
  site/docs/id/README.md
  site/docs/uk/README.md
Labels: :es: ES, :indonesia: ID, :ukraine: UK

#1112 Document paid reaction updates and mention Bot API 7.9 support
  site/docs/README.md
  site/docs/es/README.md
  site/docs/es/guide/reactions.md
  site/docs/guide/reactions.md
  site/docs/id/README.md
  site/docs/id/guide/reactions.md
  site/docs/uk/README.md
  site/docs/uk/guide/reactions.md
  site/docs/zh/README.md
  site/docs/zh/guide/reactions.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK
