Repository grammyjs/website, pull requests merged in 2024-11, with the labels that each got.

#1141 Fix typos introduced by #1139
  site/docs/advanced/flood.md
  site/docs/es/hosting/zeabur-deno.md
  site/docs/es/hosting/zeabur-nodejs.md
  site/docs/hosting/zeabur-deno.md
  site/docs/hosting/zeabur-nodejs.md
  site/docs/id/hosting/zeabur-deno.md
  site/docs/id/hosting/zeabur-nodejs.md
  site/docs/ru/hosting/zeabur-deno.md
  site/docs/ru/hosting/zeabur-nodejs.md
  site/docs/uk/hosting/zeabur-deno.md
  site/docs/uk/hosting/zeabur-nodejs.md
  site/docs/zh/hosting/zeabur-deno.md
  site/docs/zh/hosting/zeabur-nodejs.md
Labels: typo, not translatable

#1140 Translate #1139
  site/docs/es/README.md
  site/docs/es/advanced/flood.md
  site/docs/id/README.md
  site/docs/id/advanced/flood.md
  site/docs/ru/README.md
  site/docs/ru/advanced/flood.md
  site/docs/ru/plugins/keyboard.md
  site/docs/uk/README.md
  site/docs/uk/advanced/flood.md
  site/docs/zh/README.md
  site/docs/zh/advanced/flood.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK, :ru: RU

#1135 Update deps
  site/docs/.vitepress/plugins/current-versions/build-index.ts
  site/package-lock.json
  site/package.json
Labels: not translatable, chore

#1136 Update permissions for Deno 2
  site/docs/es/guide/getting-started.md
  site/docs/es/guide/introduction.md
  site/docs/es/hosting/zeabur-deno.md
  site/docs/guide/getting-started.md
  site/docs/guide/introduction.md
  site/docs/hosting/zeabur-deno.md
  site/docs/id/guide/getting-started.md
  site/docs/id/guide/introduction.md
  site/docs/id/hosting/zeabur-deno.md
  site/docs/ru/guide/getting-started.md
  site/docs/ru/guide/introduction.md
  site/docs/ru/hosting/zeabur-deno.md
  site/docs/uk/guide/getting-started.md
  site/docs/uk/guide/introduction.md
  site/docs/uk/hosting/zeabur-deno.md
  site/docs/zh/guide/getting-started.md
  site/docs/zh/guide/introduction.md
  site/docs/zh/hosting/zeabur-deno.md
Labels: not translatable

#1143 Fix CI warning and update dependencies
  .github/workflows/build.yml
  site/docs/.vitepress/config.ts
  site/docs/.vitepress/plugins/current-versions/plugins.ts
  site/package-lock.json
  site/package.json
Labels: not translatable, chore

#1145 Migrate entire website to Deno tooling
  .github/workflows/build.yml
  .github/workflows/check.yml
  .gitignore
  .vscode/settings.json
  README.md
  deno.jsonc
  site/.npmrc
  site/api/components/Function/Parameters.tsx
  site/api/components/TsType.tsx
  site/api/deno.jsonc
  site/deno.jsonc
  site/deno.lock
  site/docs/.vitepress/config.ts
  site/docs/.vitepress/plugins/better-line-breaks/plugins.ts
  site/docs/.vitepress/plugins/current-versions/plugins.ts
  site/docs/.vitepress/plugins/index.ts
  site/docs/.vitepress/plugins/markdown.ts
  site/package-lock.json
  site/package.json
  site/tsconfig.json
Labels: not translatable, chore

#1146 Remove duplicate key in VitePress config
  site/docs/.vitepress/config.ts
Labels: not translatable, chore

#1149 Fix context code examples
  site/docs/es/guide/context.md
  site/docs/guide/context.md
  site/docs/id/guide/context.md
  site/docs/ru/guide/context.md
  site/docs/uk/guide/context.md
  site/docs/zh/guide/context.md
Labels: typo, not translatable

#1151 Fix typos
  site/docs/plugins/auto-retry.md
Labels: typo, not translatable

#1150 Add missing prepositions
  site/docs/guide/api.md
Labels: typo, not translatable

#1018 Add commands plugin page
  site/docs/.vitepress/configs/locales/en.ts
  site/docs/.vitepress/configs/locales/es.ts
  site/docs/.vitepress/configs/locales/id.ts
  site/docs/.vitepress/configs/locales/ru.ts
  site/docs/.vitepress/configs/locales/uk.ts
  site/docs/.vitepress/configs/locales/zh.ts
  site/docs/.vitepress/plugins/current-versions/modules.json
  site/docs/es/guide/introduction.md
  site/docs/es/hosting/heroku.md
  site/docs/es/plugins/commands.md
  site/docs/guide/introduction.md
  site/docs/hosting/heroku.md
  site/docs/id/guide/introduction.md
  site/docs/id/hosting/heroku.md
  site/docs/id/plugins/commands.md
  site/docs/plugins/commands.md
  site/docs/ru/guide/introduction.md
  site/docs/ru/hosting/heroku.md
  site/docs/ru/plugins/commands.md
  site/docs/ru/plugins/session.md
  site/docs/uk/guide/introduction.md
  site/docs/uk/hosting/heroku.md
  site/docs/uk/hosting/vps.md
  site/docs/uk/plugins/commands.md
  site/docs/zh/guide/introduction.md
  site/docs/zh/hosting/heroku.md
  site/docs/zh/plugins/commands.md
  site/modules.ts
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK, :ru: RU

#1153 Mention support for Bot API 8.0
  site/docs/README.md
Labels: not translatable, merge on release, time-sensitive

#1144 Be more clear about using custom context types
  site/docs/es/guide/context.md
  site/docs/guide/context.md
  site/docs/id/guide/context.md
  site/docs/ru/guide/context.md
  site/docs/uk/guide/context.md
  site/docs/zh/guide/context.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK, :ru: RU

#1156 [Russian] Fix typos
  site/docs/ru/plugins/README.md
  site/docs/ru/plugins/media-group.md
Labels: not translatable, :ru: RU

#1157 Fix Blob instantiations in code examples
  site/docs/es/guide/files.md
  site/docs/guide/files.md
  site/docs/id/guide/files.md
  site/docs/ru/guide/files.md
  site/docs/uk/guide/files.md
  site/docs/zh/guide/files.md
Labels: not translatable

#1158 [Chinese] Replace redirect with direct link
  site/docs/zh/hosting/vps.md
Labels: typo, not translatable, :cn: ZH

#1154 Translate #1153
  site/docs/es/README.md
  site/docs/id/README.md
  site/docs/ru/README.md
  site/docs/uk/README.md
  site/docs/zh/README.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK, :ru: RU

#1159 Do not escape valid HTML entities
  site/docs/.vitepress/plugins/better-line-breaks/shared.ts
Labels: not translatable, chore
