Repository grammyjs/website, pull requests merged in 2024-10, with the labels that each got.

#1115 Factor in DX for comparison with Go
  site/docs/es/resources/comparison.md
  site/docs/id/resources/comparison.md
  site/docs/resources/comparison.md
  site/docs/ru/resources/comparison.md
  site/docs/uk/resources/comparison.md
  site/docs/zh/resources/comparison.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK, :ru: RU

#1131 Use Deno 2.0 with CI
  .github/workflows/check.yml
Labels: not translatable, chore

#1133 Format newly supported files by deno fmt
  site/docs/.vitepress/theme/style/_custom-block.scss
  site/docs/.vitepress/theme/style/_fonts.scss
  site/docs/.vitepress/theme/style/_normalize.scss
  site/docs/.vitepress/theme/style/_vars.scss
  site/docs/README.md
  site/docs/es/README.md
  site/docs/es/hosting/fly.md
  site/docs/hosting/fly.md
  site/docs/id/README.md
  site/docs/id/hosting/fly.md
  site/docs/ru/hosting/fly.md
  site/docs/uk/README.md
  site/docs/uk/hosting/fly.md
  site/docs/zh/README.md
  site/docs/zh/hosting/fly.md
Labels: not translatable, chore

#1137 Fix typos
  site/docs/resources/faq.md
Labels: typo, not translatable, style

#1138 Fix typo
  site/docs/advanced/flood.md
Labels: typo, not translatable

#1130 Mention that bots have to be admin for reaction updates
  site/docs/es/guide/reactions.md
  site/docs/guide/reactions.md
  site/docs/id/guide/reactions.md
  site/docs/ru/guide/reactions.md
  site/docs/uk/guide/reactions.md
  site/docs/zh/guide/reactions.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK, :ru: RU

#1139 Add section about paid broadcasts and mention support for Bot API 7.11
  site/docs/README.md
  site/docs/advanced/flood.md
  site/modules.ts
Labels: merge on release, time-sensitive
