Repository grammyjs/website, pull requests merged in 2025-08, with the labels that each got.

#1207 Add examples of editing messages to Telegram Business docs (#1202)
  site/docs/advanced/business.md
  site/docs/es/advanced/business.md
  site/docs/id/advanced/business.md
  site/docs/ru/advanced/business.md
  site/docs/uk/advanced/business.md
  site/docs/zh/advanced/business.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK, :ru: RU

#1227 Pin Deno version
  .github/workflows/build.yml
  .github/workflows/check.yml
Labels: not translatable, chore

#1228 Change Deno version used in CI
  .github/workflows/build.yml
  .github/workflows/check.yml
Labels: not translatable, chore

#1226 Mention support for Bot API 9.2
  site/docs/README.md
  site/docs/uk/README.md
Labels: not translatable, :ukraine: UK, time-sensitive

#1224 Fix command plugin code example
  site/docs/es/plugins/commands.md
  site/docs/id/plugins/commands.md
  site/docs/plugins/commands.md
  site/docs/ru/plugins/commands.md
  site/docs/uk/plugins/commands.md
  site/docs/zh/plugins/commands.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK, :ru: RU

#1189 Fixes for the commands plugin (#1142 but only the fixes)
  site/docs/es/plugins/commands.md
  site/docs/id/README.md
  site/docs/id/plugins/commands.md
  site/docs/plugins/commands.md
  site/docs/ru/plugins/commands.md
  site/docs/uk/plugins/commands.md
  site/docs/zh/plugins/commands.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK, :ru: RU

#1229 Translate #1226
  site/docs/es/README.md
  site/docs/id/README.md
  site/docs/ru/README.md
  site/docs/zh/README.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK, :ru: RU

#1230 Set nodeModulesDir to manual
  .github/workflows/build.yml
  .github/workflows/check.yml
  site/deno.jsonc
  site/docs/.vitepress/theme/style/_fonts.scss
  site/docs/public/icons/beach.svg
  site/docs/public/icons/palette.svg
  site/docs/public/icons/rocket.svg
  site/docs/public/images/Y.svg
  site/docs/public/images/grammY.svg
Labels: not translatable, chore
