Repository grammyjs/website, pull requests merged in 2025-01, with the labels that each got.

#1175 Mention support for Bot API 8.2
  site/docs/README.md
Labels: not translatable, merge on release, time-sensitive

#1177 Update copyright years
  LICENSE
  site/docs/README.md
  site/docs/es/README.md
  site/docs/id/README.md
  site/docs/ru/README.md
  site/docs/uk/README.md
  site/docs/zh/README.md
Labels: not translatable

#1176 Translate #1175
  site/docs/es/README.md
  site/docs/id/README.md
  site/docs/ru/README.md
  site/docs/uk/README.md
  site/docs/zh/README.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK, :ru: RU

#1174 Translate #1161
  site/docs/es/hosting/comparison.md
  site/docs/hosting/comparison.md
  site/docs/id/hosting/comparison.md
  site/docs/ru/hosting/comparison.md
  site/docs/uk/hosting/comparison.md
  site/docs/zh/hosting/comparison.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK, :ru: RU

#1178 Grammy entity zh
  site/docs/.vitepress/configs/locales/zh.ts
  site/docs/zh/plugins/entity-parser.md
Labels: :cn: ZH

#1121 Add Entity Parser plugin docs
  site/docs/.vitepress/configs/locales/en.ts
  site/docs/.vitepress/configs/locales/es.ts
  site/docs/.vitepress/configs/locales/id.ts
  site/docs/.vitepress/configs/locales/ru.ts
  site/docs/.vitepress/configs/locales/uk.ts
  site/docs/.vitepress/configs/locales/zh.ts
  site/docs/es/plugins/entity-parser.md
  site/docs/id/plugins/entity-parser.md
  site/docs/plugins/entity-parser.md
  site/docs/ru/plugins/entity-parser.md
  site/docs/uk/plugins/entity-parser.md
  site/docs/zh/plugins/entity-parser.md
Labels: ready for translation, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK, :ru: RU

#1180 Update API reference generator's dependencies
  site/api/api_gen.tsx
  site/api/components/Class.tsx
  site/api/components/Class/Constructors.tsx
  site/api/components/Class/Method.tsx
  site/api/components/Function.tsx
  site/api/components/Function/Parameters.tsx
  site/api/components/Function/ReturnType.tsx
  site/api/components/Interface.tsx
  site/api/components/Loc.tsx
  site/api/components/Properties.tsx
  site/api/components/ToC.tsx
  site/api/components/TsType.tsx
  site/api/components/TypeAlias.tsx
  site/api/components/TypeParams.tsx
  site/api/components/Variable.tsx
  site/api/components/util.ts
  site/api/deno.jsonc
  site/api/types.ts
Labels: not translatable, chore

#1184 [Chinese] Remove English content
  site/docs/zh/advanced/business.md
Labels: not translatable, :cn: ZH
