Repository grammyjs/website, pull requests merged in 2025-03, with the labels that each got.

#1183 Merge fmt and lint CI jobs
  .github/workflows/check.yml
Labels: not translatable

#1199 Fix typo in FAQ
  site/docs/resources/faq.md
Labels: typo, not translatable

#1206 Lint
  site/api/components/CodeBlock.tsx
  site/api/components/TsType.tsx
  site/api/components/TypeAlias.tsx
  site/deno.jsonc
Labels: typo, not translatable, style, chore

#1203 [Chinese] Fix typos
  site/docs/zh/advanced/transformers.md
Labels: typo, not translatable, :cn: ZH

#1205 Fix parameters passed to setMessageReaction
  site/docs/es/guide/reactions.md
  site/docs/guide/reactions.md
  site/docs/id/guide/reactions.md
  site/docs/ru/guide/reactions.md
  site/docs/uk/guide/reactions.md
  site/docs/zh/guide/reactions.md
Labels: not translatable, :es: ES, :cn: ZH, :indonesia: ID, :ukraine: UK, :ru: RU
